-- Example 21: per-test database isolation (template clones).
--
-- Repeatable migration (R__): drops and recreates everything. In the test workflow this is applied ONCE to
-- the TEMPLATE database (see test-config.json → Steps.MigrateTemplate); the shared test database and any
-- per-test isolated databases are then created as clones of that template (`create database ... template ...`).

drop schema if exists example_21 cascade;
create schema example_21;

create table example_21.users (
    id    int generated by default as identity primary key,
    name  text not null,
    email text not null unique
);

insert into example_21.users (id, name, email) values
    (1, 'Ada Lovelace',  'ada@example.com'),
    (2, 'Alan Turing',   'alan@example.com'),
    (3, 'Grace Hopper',  'grace@example.com');

-- Explicit-id seed inserts do NOT advance the identity sequence; set it so the next default id is exactly 4.
-- This is what makes sequence values deterministic in a freshly cloned database.
select setval(pg_get_serial_sequence('example_21.users', 'id'), 3, true);
