// autogenerated at 2026-01-03T11:49:10.4116160+01:00


const baseUrl = "http://127.0.0.1:8080";

interface IGetUsersResponse {
    userId: number | null;
    username: string | null;
    email: string | null;
    roles: string[] | null;
    passwordHash: string | null;
    lastLogin: string | null;
    lastLoginProvider: string | null;
    isThisMe: boolean | null;
}

interface ILoginRequest {
    scheme: string | null;
    username: string | null;
    password: string | null;
}

interface IWhoAmIResponse {
    userId: number | null;
    username: string | null;
    email: string | null;
    roles: string[] | null;
    lastLogin: string | null;
    lastLoginProvider: string | null;
}


/**
* function example_4.get_users()
* returns table(
*     users integer,
*     users text,
*     users text,
*     users text[],
*     users text,
*     users timestamp with time zone,
*     users text,
*     is_this_me boolean
* )
* 
* @remarks
* comment on function example_4.get_users is 'HTTP GET
* authorize admin';
* 
* @param parseRequest - Optional function to parse constructed request before making the request.
* @returns {status: number, response: IGetUsersResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_4.get_users
*/
export async function getUsers(
    parseRequest: (request: RequestInit) => RequestInit = request => request
) : Promise<{status: number, response: IGetUsersResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-4/get-users", parseRequest({
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    }));
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetUsersResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_4.login(
*     _scheme text,
*     _username text,
*     _password text
* )
* returns table(
*     scheme text,
*     user_id integer,
*     username text,
*     roles text[],
*     email text,
*     password_hash text
* )
* 
* @remarks
* comment on function example_4.login is 'HTTP POST
* login
* anonymous';
* 
* @param request - Object containing request parameters.
* @param parseRequest - Optional function to parse constructed request before making the request.
* @returns {status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_4.login
*/
export async function login(
    request: ILoginRequest,
    parseRequest: (request: RequestInit) => RequestInit = request => request
) : Promise<{status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-4/login", parseRequest({
        method: "POST",
        body: JSON.stringify(request)
    }));
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_4.logout()
* returns void
* 
* @remarks
* comment on function example_4.logout is 'HTTP POST
* logout
* authorize';
* 
* @param parseRequest - Optional function to parse constructed request before making the request.
* @returns {status: number, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_4.logout
*/
export async function logout(
    parseRequest: (request: RequestInit) => RequestInit = request => request
) : Promise<{status: number, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-4/logout", parseRequest({
        method: "POST",
    }));
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_4.who_am_i()
* returns record
* 
* @remarks
* comment on function example_4.who_am_i is 'HTTP GET
* authorize';
* 
* @param parseRequest - Optional function to parse constructed request before making the request.
* @returns {status: number, response: IWhoAmIResponse, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_4.who_am_i
*/
export async function whoAmI(
    parseRequest: (request: RequestInit) => RequestInit = request => request
) : Promise<{status: number, response: IWhoAmIResponse, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-4/who-am-i", parseRequest({
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    }));
    return {
        status: response.status,
        response: response.ok ? await response.json() as IWhoAmIResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

