// autogenerated at 2026-01-04T12:51:43.8980920+01:00


const baseUrl = "http://127.0.0.1:8080";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

interface IGetMyUploadsRequest {
    userId?: string | null;
}

interface IGetMyUploadsResponse {
    id: number | null;
    userId: number | null;
    fileName: string | null;
    contentType: string | null;
    fileSize: number | null;
    oid: number | null;
    filePath: string | null;
    uploadedAt: string | null;
}

interface ILoginRequest {
    username: string | null;
    password: string | null;
}

interface IUploadToCombinedRequest {
    userId?: string | null;
    meta?: string | null;
}

interface IUploadToCombinedResponse {
    type: string;
    fileName: string;
    contentType: string;
    size: number;
    success: boolean;
    status: string;
    [key: string]: string | number | boolean;
}

interface IUploadToFileSystemRequest {
    userId?: string | null;
    meta?: string | null;
}

interface IUploadToFileSystemResponse {
    type: string;
    fileName: string;
    contentType: string;
    size: number;
    success: boolean;
    status: string;
    [key: string]: string | number | boolean;
}

interface IUploadToLargeObjectRequest {
    userId?: string | null;
    meta?: string | null;
}

interface IUploadToLargeObjectResponse {
    type: string;
    fileName: string;
    contentType: string;
    size: number;
    success: boolean;
    status: string;
    [key: string]: string | number | boolean;
}


/**
* function example_6.get_my_uploads(
*     _user_id text DEFAULT NULL::text
* )
* returns table(
*     id integer,
*     user_id integer,
*     file_name text,
*     content_type text,
*     file_size bigint,
*     oid bigint,
*     file_path text,
*     uploaded_at timestamp with time zone
* )
* 
* @remarks
* comment on function example_6.get_my_uploads is 'HTTP GET
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IGetMyUploadsResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_6.get_my_uploads
*/
export async function getMyUploads(
    request: IGetMyUploadsRequest
) : Promise<{status: number, response: IGetMyUploadsResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-6/get-my-uploads" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetMyUploadsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_6.login(
*     _username text,
*     _password text
* )
* returns table(
*     scheme text,
*     user_id integer,
*     username text
* )
* 
* @remarks
* comment on function example_6.login is 'HTTP POST
* login
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_6.login
*/
export async function login(
    request: ILoginRequest
) : Promise<{status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-6/login", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_6.logout()
* returns void
* 
* @remarks
* comment on function example_6.logout is 'HTTP POST
* logout
* authorize';
* 
* @returns {status: number, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_6.logout
*/
export async function logout() : Promise<{status: number, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-6/logout", {
        method: "POST",
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_6.upload_to_combined(
*     _user_id text DEFAULT NULL::text,
*     _meta json DEFAULT NULL::json
* )
* returns table(
*     success boolean,
*     status text,
*     file_name text,
*     content_type text,
*     file_size bigint,
*     oid bigint,
*     file_path text
* )
* 
* @remarks
* comment on function example_6.upload_to_combined is 'HTTP POST
* upload for large_object, file_system
* param _meta is upload metadata
* check_image = true
* path = ./6_image_uploads/public/uploads
* unique_name = true
* create_path = true';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IUploadToCombinedResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_6.upload_to_combined
*/
export async function uploadToCombined(
    files: FileList | null,
    request: IUploadToCombinedRequest,
    progress?: (loaded: number, total: number) => void,
): Promise<{status: number, response: IUploadToCombinedResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    return new Promise((resolve, reject) => {
        if (!files || files.length === 0) {
            reject(new Error("No files to upload"));
            return;
        }
        var xhr = new XMLHttpRequest();
        if (progress) {
            xhr.upload.addEventListener(
                "progress",
                (event) => {
                    if (event.lengthComputable && progress) {
                        progress(event.loaded, event.total);
                    }
                },
                false
            );
        }
        xhr.onload = function () {
            if (this.status >= 200 && this.status < 300) {
                resolve({status: this.status, response: JSON.parse(this.responseText) as IUploadToCombinedResponse[], error: undefined});
            } else {
                resolve({status: this.status, response: [], error: JSON.parse(this.responseText) as {status: number; title: string; detail?: string | null}});
            }
        };
        xhr.onerror = function () {
            reject({
                xhr: this, 
                status: this.status,
                statusText: this.statusText || 'Network error occurred',
                response: this.response
            });
        };
        xhr.open("POST", baseUrl + "/api/example-6/upload-to-combined" + parseQuery(request));
        const formData = new FormData();
        for(let i = 0; i < files.length; i++) {
            const file = files[i];
            formData.append("file", file, file.name);
        }
        xhr.send(formData);
    });
}

/**
* function example_6.upload_to_file_system(
*     _user_id text DEFAULT NULL::text,
*     _meta json DEFAULT NULL::json
* )
* returns table(
*     success boolean,
*     status text,
*     file_name text,
*     content_type text,
*     file_size bigint,
*     oid bigint,
*     file_path text
* )
* 
* @remarks
* comment on function example_6.upload_to_file_system is 'HTTP POST
* upload for file_system
* param _meta is upload metadata
* check_image = true
* path = ./6_image_uploads/public/uploads
* unique_name = true
* create_path = true';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IUploadToFileSystemResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_6.upload_to_file_system
*/
export async function uploadToFileSystem(
    files: FileList | null,
    request: IUploadToFileSystemRequest,
    progress?: (loaded: number, total: number) => void,
): Promise<{status: number, response: IUploadToFileSystemResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    return new Promise((resolve, reject) => {
        if (!files || files.length === 0) {
            reject(new Error("No files to upload"));
            return;
        }
        var xhr = new XMLHttpRequest();
        if (progress) {
            xhr.upload.addEventListener(
                "progress",
                (event) => {
                    if (event.lengthComputable && progress) {
                        progress(event.loaded, event.total);
                    }
                },
                false
            );
        }
        xhr.onload = function () {
            if (this.status >= 200 && this.status < 300) {
                resolve({status: this.status, response: JSON.parse(this.responseText) as IUploadToFileSystemResponse[], error: undefined});
            } else {
                resolve({status: this.status, response: [], error: JSON.parse(this.responseText) as {status: number; title: string; detail?: string | null}});
            }
        };
        xhr.onerror = function () {
            reject({
                xhr: this, 
                status: this.status,
                statusText: this.statusText || 'Network error occurred',
                response: this.response
            });
        };
        xhr.open("POST", baseUrl + "/api/example-6/upload-to-file-system" + parseQuery(request));
        const formData = new FormData();
        for(let i = 0; i < files.length; i++) {
            const file = files[i];
            formData.append("file", file, file.name);
        }
        xhr.send(formData);
    });
}

/**
* function example_6.upload_to_large_object(
*     _user_id text DEFAULT NULL::text,
*     _meta json DEFAULT NULL::json
* )
* returns table(
*     success boolean,
*     status text,
*     file_name text,
*     content_type text,
*     file_size bigint,
*     oid bigint,
*     file_path text
* )
* 
* @remarks
* comment on function example_6.upload_to_large_object is 'HTTP POST
* upload for large_object
* param _meta is upload metadata
* check_image = true';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IUploadToLargeObjectResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_6.upload_to_large_object
*/
export async function uploadToLargeObject(
    files: FileList | null,
    request: IUploadToLargeObjectRequest,
    progress?: (loaded: number, total: number) => void,
): Promise<{status: number, response: IUploadToLargeObjectResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    return new Promise((resolve, reject) => {
        if (!files || files.length === 0) {
            reject(new Error("No files to upload"));
            return;
        }
        var xhr = new XMLHttpRequest();
        if (progress) {
            xhr.upload.addEventListener(
                "progress",
                (event) => {
                    if (event.lengthComputable && progress) {
                        progress(event.loaded, event.total);
                    }
                },
                false
            );
        }
        xhr.onload = function () {
            if (this.status >= 200 && this.status < 300) {
                resolve({status: this.status, response: JSON.parse(this.responseText) as IUploadToLargeObjectResponse[], error: undefined});
            } else {
                resolve({status: this.status, response: [], error: JSON.parse(this.responseText) as {status: number; title: string; detail?: string | null}});
            }
        };
        xhr.onerror = function () {
            reject({
                xhr: this, 
                status: this.status,
                statusText: this.statusText || 'Network error occurred',
                response: this.response
            });
        };
        xhr.open("POST", baseUrl + "/api/example-6/upload-to-large-object" + parseQuery(request));
        const formData = new FormData();
        for(let i = 0; i < files.length; i++) {
            const file = files[i];
            formData.append("file", file, file.name);
        }
        xhr.send(formData);
    });
}

