// autogenerated at 2026-03-28T12:03:45.0779510+01:00
const baseUrl = "";

interface IMyFirstQueryResponse {
    first: string[];
    second: { queryText: string, user: string, timestamp: Date }[];
}


/**
* SQL: my-first-query
* 
* @remarks
* comment on function public.my-first-query is ' HTTP GET
*  @result1 first
*  @result2 second';
* 
* @returns {status: number, response: IMyFirstQueryResponse, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see SQLFILE public.my-first-query
*/
export async function myFirstQuery() : Promise<{status: number, response: IMyFirstQueryResponse, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/my-first-query", {
        method: "GET",
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IMyFirstQueryResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

