// autogenerated at 2026-03-31T18:26:11.9489470+02:00


const baseUrl = "";

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

interface IMyFirstQueryResponse {
    first: string[];
    second: { queryText: string, user: string, timestamp: Date };
}


/**
* SQL file: ../../npgsqlrest-docs/examples/1_my_first_function_sql_file/sql/my-first-query.sql
* 
* @remarks
*  HTTP GET
*  @result first
*  @result second
*  @single
* 
* @returns {ApiResult<IMyFirstQueryResponse>}
* 
* @see SQLFILE public.my-first-query
*/
export async function myFirstQuery() : Promise<ApiResult<IMyFirstQueryResponse>> {
    const response = await fetch(baseUrl + "/api/my-first-query", {
        method: "GET",
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IMyFirstQueryResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

