// autogenerated at 2026-04-01T11:43:26.6135140+02:00


const baseUrl = "";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

interface ICombinedUploadRequest {
    meta?: string | null;
}

interface ICombinedUploadResponse {
    type: string;
    fileName: string;
    contentType: string;
    size: number;
    success: boolean;
    status: string;
    [key: string]: string | number | boolean;
}

interface ICsvUploadRequest {
    meta?: string | null;
}

interface ICsvUploadResponse {
    type: string;
    fileName: string;
    contentType: string;
    size: number;
    success: boolean;
    status: string;
    [key: string]: string | number | boolean;
}

interface IExcelUploadRequest {
    meta?: string | null;
}

interface IExcelUploadResponse {
    type: string;
    fileName: string;
    contentType: string;
    size: number;
    success: boolean;
    status: string;
    [key: string]: string | number | boolean;
}

interface IGetUploadDataRequest {
    type: string | null;
    _user_id?: string | null;
}

interface ILoginRequest {
    username: string | null;
    password: string | null;
}


/**
* SQL file: ./7_csv_excel_uploads_sql_file/sql/combined-upload.sql
* 
* @remarks
* HTTP POST
* @authorize
* @upload for excel
* @param $1 meta json = null
* @param meta is upload metadata
* @all_sheets = true
* @fallback_handler = csv
* @row_command = select example_7.combined_upload_row($1,$2,$3,$4)
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<ICombinedUploadResponse[]>}
*/
export async function combinedUpload(
    files: FileList | null,
    request: ICombinedUploadRequest,
    progress?: (loaded: number, total: number) => void,
): Promise<ApiResult<ICombinedUploadResponse[]>> {
    return new Promise((resolve, reject) => {
        if (!files || files.length === 0) {
            reject(new Error("No files to upload"));
            return;
        }
        var xhr = new XMLHttpRequest();
        if (progress) {
            xhr.upload.addEventListener(
                "progress",
                (event) => {
                    if (event.lengthComputable && progress) {
                        progress(event.loaded, event.total);
                    }
                },
                false
            );
        }
        xhr.onload = function () {
            if (this.status >= 200 && this.status < 300) {
                resolve({status: this.status, response: JSON.parse(this.responseText) as ICombinedUploadResponse[], error: undefined});
            } else {
                resolve({status: this.status, response: [], error: JSON.parse(this.responseText) as ApiError});
            }
        };
        xhr.onerror = function () {
            reject({
                xhr: this, 
                status: this.status,
                statusText: this.statusText || 'Network error occurred',
                response: this.response
            });
        };
        xhr.open("POST", baseUrl + "/api/combined-upload" + parseQuery(request));
        const formData = new FormData();
        for(let i = 0; i < files.length; i++) {
            const file = files[i];
            formData.append("file", file, file.name);
        }
        xhr.send(formData);
    });
}

/**
* SQL file: ./7_csv_excel_uploads_sql_file/sql/csv-upload.sql
* 
* @remarks
* HTTP POST
* @authorize
* @upload for csv
* @param $1 meta json = null
* @param meta is upload metadata
* @delimiters = ,;
* @row_command = select example_7.csv_upload_row($1,$2,$3,$4)
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<ICsvUploadResponse[]>}
*/
export async function csvUpload(
    files: FileList | null,
    request: ICsvUploadRequest,
    progress?: (loaded: number, total: number) => void,
): Promise<ApiResult<ICsvUploadResponse[]>> {
    return new Promise((resolve, reject) => {
        if (!files || files.length === 0) {
            reject(new Error("No files to upload"));
            return;
        }
        var xhr = new XMLHttpRequest();
        if (progress) {
            xhr.upload.addEventListener(
                "progress",
                (event) => {
                    if (event.lengthComputable && progress) {
                        progress(event.loaded, event.total);
                    }
                },
                false
            );
        }
        xhr.onload = function () {
            if (this.status >= 200 && this.status < 300) {
                resolve({status: this.status, response: JSON.parse(this.responseText) as ICsvUploadResponse[], error: undefined});
            } else {
                resolve({status: this.status, response: [], error: JSON.parse(this.responseText) as ApiError});
            }
        };
        xhr.onerror = function () {
            reject({
                xhr: this, 
                status: this.status,
                statusText: this.statusText || 'Network error occurred',
                response: this.response
            });
        };
        xhr.open("POST", baseUrl + "/api/csv-upload" + parseQuery(request));
        const formData = new FormData();
        for(let i = 0; i < files.length; i++) {
            const file = files[i];
            formData.append("file", file, file.name);
        }
        xhr.send(formData);
    });
}

/**
* SQL file: ./7_csv_excel_uploads_sql_file/sql/excel-upload.sql
* 
* @remarks
* HTTP POST
* @authorize
* @upload for excel
* @param $1 meta json = null
* @param meta is upload metadata
* @all_sheets = true
* @row_command = select example_7.excel_upload_row($1,$2,$3,$4)
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IExcelUploadResponse[]>}
*/
export async function excelUpload(
    files: FileList | null,
    request: IExcelUploadRequest,
    progress?: (loaded: number, total: number) => void,
): Promise<ApiResult<IExcelUploadResponse[]>> {
    return new Promise((resolve, reject) => {
        if (!files || files.length === 0) {
            reject(new Error("No files to upload"));
            return;
        }
        var xhr = new XMLHttpRequest();
        if (progress) {
            xhr.upload.addEventListener(
                "progress",
                (event) => {
                    if (event.lengthComputable && progress) {
                        progress(event.loaded, event.total);
                    }
                },
                false
            );
        }
        xhr.onload = function () {
            if (this.status >= 200 && this.status < 300) {
                resolve({status: this.status, response: JSON.parse(this.responseText) as IExcelUploadResponse[], error: undefined});
            } else {
                resolve({status: this.status, response: [], error: JSON.parse(this.responseText) as ApiError});
            }
        };
        xhr.onerror = function () {
            reject({
                xhr: this, 
                status: this.status,
                statusText: this.statusText || 'Network error occurred',
                response: this.response
            });
        };
        xhr.open("POST", baseUrl + "/api/excel-upload" + parseQuery(request));
        const formData = new FormData();
        for(let i = 0; i < files.length; i++) {
            const file = files[i];
            formData.append("file", file, file.name);
        }
        xhr.send(formData);
    });
}

/**
* SQL file: ./7_csv_excel_uploads_sql_file/sql/get-upload-data.sql
* 
* @remarks
* HTTP GET
* @authorize
* @param $1 type text
* @param $2 _user_id text = null
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<string[][]>}
*/
export async function getUploadData(
    request: IGetUploadDataRequest
) : Promise<ApiResult<string[][]>> {
    const response = await fetch(baseUrl + "/api/get-upload-data" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as string[][] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ./7_csv_excel_uploads_sql_file/sql/login.sql
* 
* @remarks
* HTTP POST
* @login
* @anonymous
* @param $1 username
* @param $2 password
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<string>}
*/
export async function login(
    request: ILoginRequest
) : Promise<ApiResult<string>> {
    const response = await fetch(baseUrl + "/api/login", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ./7_csv_excel_uploads_sql_file/sql/logout.sql
* 
* @remarks
*  HTTP POST
*  @logout
*  @authorize
* 
* @returns {status: number, error: ApiError | undefined}
*/
export async function logout() : Promise<{status: number, error: ApiError | undefined}> {
    const response = await fetch(baseUrl + "/api/logout", {
        method: "POST",
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

