@host=http://127.0.0.1:8080

// function example_17.average_book_price(
//     _response_body text DEFAULT NULL::example_17.books_api,
//     _response_status_code integer,
//     _response_success boolean,
//     _response_error_message text
// )
// returns table(
//     avg_price numeric
// )
//
// comment on function example_17.average_book_price is 'HTTP GET /average-book-price
// @allow_anonymous
// @single';
GET {{host}}/average-book-price?responseBody=ABC&responseStatusCode=2&responseSuccess=false&responseErrorMessage=ABC

###

