// autogenerated at 2026-06-26T12:08:33.9114500+02:00


const baseUrl = "";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

interface IAiAnalyzeRequest {
    text: string | null;
    maxLength?: number | null;
    maxKeywords?: number | null;
    proxyStatusCode?: number | null;
    proxyBody?: string | null;
    proxySuccess?: boolean | null;
    proxyErrorMessage?: string | null;
}

interface IAiSentimentRequest {
    text: string | null;
    proxyStatusCode?: number | null;
    proxyBody?: string | null;
    proxySuccess?: boolean | null;
    proxyErrorMessage?: string | null;
}

interface IAiSummarizeRequest {
    text: string | null;
    maxLength?: number | null;
    proxyStatusCode?: number | null;
    proxyBody?: string | null;
    proxySuccess?: boolean | null;
    proxyErrorMessage?: string | null;
}

interface ICacheEntriesRequest {
    limit?: number | null;
}

interface ICacheEntriesResponse {
    id: number | null;
    textPreview: string | null;
    hasSummary: boolean | null;
    sentiment: string | null;
    keywords: string[] | null;
    accessedCount: number | null;
    createdAt: string | null;
}

interface ICacheStatsResponse {
    totalCached: number | null;
    totalCacheHits: number | null;
    mostAccessedPreview: string | null;
    mostAccessedHits: number | null;
    oldestEntry: string | null;
    newestEntry: string | null;
}

interface ILoginRequest {
    username: string | null;
    password: string | null;
}


/**
* function example_10.ai_analyze(
*     _text text,
*     _max_length integer DEFAULT 150,
*     _max_keywords integer DEFAULT 5,
*     _proxy_status_code integer DEFAULT NULL::integer,
*     _proxy_body text DEFAULT NULL::text,
*     _proxy_success boolean DEFAULT NULL::boolean,
*     _proxy_error_message text DEFAULT NULL::text
* )
* returns json
* 
* @remarks
* comment on function example_10.ai_analyze is 'HTTP POST /ai/analyze
* authorize
* proxy POST';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<any>}
* 
* @see FUNCTION example_10.ai_analyze
*/
export async function aiAnalyze(
    request: IAiAnalyzeRequest
) : Promise<ApiResult<any>> {
    const response = await fetch(baseUrl + "/ai/analyze", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function example_10.ai_health()
* returns void
* 
* @remarks
* comment on function example_10.ai_health is 'HTTP GET /ai/health
* proxy';
* 
* @returns {ApiResult<Response>}
* 
* @see FUNCTION example_10.ai_health
*/
export async function aiHealth() : Promise<ApiResult<Response>> {
    const response = await fetch(baseUrl + "/ai/health", {
        method: "GET",
    });
    return response;
}

/**
* function example_10.ai_sentiment(
*     _text text,
*     _proxy_status_code integer DEFAULT NULL::integer,
*     _proxy_body text DEFAULT NULL::text,
*     _proxy_success boolean DEFAULT NULL::boolean,
*     _proxy_error_message text DEFAULT NULL::text
* )
* returns json
* 
* @remarks
* comment on function example_10.ai_sentiment is 'HTTP POST /ai/sentiment
* authorize
* proxy POST';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<any>}
* 
* @see FUNCTION example_10.ai_sentiment
*/
export async function aiSentiment(
    request: IAiSentimentRequest
) : Promise<ApiResult<any>> {
    const response = await fetch(baseUrl + "/ai/sentiment", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function example_10.ai_summarize(
*     _text text,
*     _max_length integer DEFAULT 150,
*     _proxy_status_code integer DEFAULT NULL::integer,
*     _proxy_body text DEFAULT NULL::text,
*     _proxy_success boolean DEFAULT NULL::boolean,
*     _proxy_error_message text DEFAULT NULL::text
* )
* returns json
* 
* @remarks
* comment on function example_10.ai_summarize is 'HTTP POST /ai/summarize
* authorize
* proxy POST';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<any>}
* 
* @see FUNCTION example_10.ai_summarize
*/
export async function aiSummarize(
    request: IAiSummarizeRequest
) : Promise<ApiResult<any>> {
    const response = await fetch(baseUrl + "/ai/summarize", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function example_10.cache_clear()
* returns json
* 
* @remarks
* comment on function example_10.cache_clear is 'HTTP DELETE /cache/clear
* authorize';
* 
* @returns {ApiResult<any>}
* 
* @see FUNCTION example_10.cache_clear
*/
export async function cacheClear() : Promise<ApiResult<any>> {
    const response = await fetch(baseUrl + "/cache/clear", {
        method: "DELETE",
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function example_10.cache_entries(
*     _limit integer DEFAULT 10
* )
* returns table(
*     id integer,
*     text_preview text,
*     has_summary boolean,
*     sentiment text,
*     keywords text[],
*     accessed_count integer,
*     created_at timestamp with time zone
* )
* 
* @remarks
* comment on function example_10.cache_entries is 'HTTP GET /cache/entries
* authorize';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<ICacheEntriesResponse[]>}
* 
* @see FUNCTION example_10.cache_entries
*/
export async function cacheEntries(
    request: ICacheEntriesRequest
) : Promise<ApiResult<ICacheEntriesResponse[]>> {
    const response = await fetch(baseUrl + "/cache/entries" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as ICacheEntriesResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function example_10.cache_stats()
* returns table(
*     total_cached bigint,
*     total_cache_hits bigint,
*     most_accessed_preview text,
*     most_accessed_hits integer,
*     oldest_entry timestamp with time zone,
*     newest_entry timestamp with time zone
* )
* 
* @remarks
* comment on function example_10.cache_stats is 'HTTP GET /cache/stats
* authorize';
* 
* @returns {ApiResult<ICacheStatsResponse[]>}
* 
* @see FUNCTION example_10.cache_stats
*/
export async function cacheStats() : Promise<ApiResult<ICacheStatsResponse[]>> {
    const response = await fetch(baseUrl + "/cache/stats", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as ICacheStatsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function example_10.login(
*     _username text,
*     _password text
* )
* returns table(
*     scheme text,
*     user_id integer,
*     user_name text
* )
* 
* @remarks
* comment on function example_10.login is 'HTTP POST
* login
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<string>}
* 
* @see FUNCTION example_10.login
*/
export async function login(
    request: ILoginRequest
) : Promise<ApiResult<string>> {
    const response = await fetch(baseUrl + "/api/example-10/login", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function example_10.logout()
* returns void
* 
* @remarks
* comment on function example_10.logout is 'HTTP POST
* logout';
* 
* @returns {status: number, error: ApiError | undefined}
* 
* @see FUNCTION example_10.logout
*/
export async function logout() : Promise<{status: number, error: ApiError | undefined}> {
    const response = await fetch(baseUrl + "/api/example-10/logout", {
        method: "POST",
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

