// autogenerated at 2026-01-06T12:03:59.3441010+01:00


const baseUrl = "http://127.0.0.1:8080";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

interface IGetFinancialDashboardRequest {
    baseCurrency: string | null;
    targetCurrenciesCsv: string | null;
    cryptoIdsCsv: string | null;
    vsCurrenciesCsv: string | null;
    exchangeRateResponseBody?: string | null;
    exchangeRateResponseStatusCode?: number | null;
    exchangeRateResponseSuccess?: boolean | null;
    exchangeRateResponseErrorMessage?: string | null;
    cryptoResponseBody?: string | null;
    cryptoResponseStatusCode?: number | null;
    cryptoResponseSuccess?: boolean | null;
    cryptoResponseErrorMessage?: string | null;
}

interface IGetFinancialDashboardResponse {
    fiatBaseCurrency: string | null;
    fiatRates: any; // JSON
    fiatLastUpdated: string | null;
    fiatSuccess: boolean | null;
    fiatError: string | null;
    cryptoPrices: any; // JSON
    cryptoSuccess: boolean | null;
    cryptoError: string | null;
}

interface ILoginRequest {
    username: string | null;
    password: string | null;
}


/**
* function example_9.get_financial_dashboard(
*     _base_currency text,
*     _target_currencies_csv text,
*     _crypto_ids_csv text,
*     _vs_currencies_csv text,
*     _exchange_rate_response_body jsonb,
*     _exchange_rate_response_status_code integer,
*     _exchange_rate_response_success boolean,
*     _exchange_rate_response_error_message text,
*     _crypto_response_body jsonb,
*     _crypto_response_status_code integer,
*     _crypto_response_success boolean,
*     _crypto_response_error_message text
* )
* returns record
* 
* @remarks
* comment on function example_9.get_financial_dashboard is 'HTTP GET /financial-dashboard
* authorize';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IGetFinancialDashboardResponse, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_9.get_financial_dashboard
*/
export async function getFinancialDashboard(
    request: IGetFinancialDashboardRequest
) : Promise<{status: number, response: IGetFinancialDashboardResponse, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/financial-dashboard" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetFinancialDashboardResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_9.login(
*     _username text,
*     _password text
* )
* returns table(
*     scheme text,
*     user_id integer,
*     user_name text
* )
* 
* @remarks
* comment on function example_9.login is 'HTTP POST
* login
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_9.login
*/
export async function login(
    request: ILoginRequest
) : Promise<{status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-9/login", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_9.logout()
* returns void
* 
* @remarks
* comment on function example_9.logout is 'HTTP POST
* logout';
* 
* @returns {status: number, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_9.logout
*/
export async function logout() : Promise<{status: number, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-9/logout", {
        method: "POST",
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

