// autogenerated at 2026-04-01T16:17:28.6822650+02:00


const baseUrl = "";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

interface IFinancialDashboardRequest {
    _base_currency: string | null;
    _target_currencies_csv: string | null;
    _crypto_ids_csv: string | null;
    _vs_currencies_csv: string | null;
    _exchange_rate_response?: string | null;
    _crypto_response?: string | null;
}

interface IFinancialDashboardResponse {
    dashboard: { fiatBaseCurrency: string, fiatRates: any, fiatLastUpdated: string, fiatSuccess: boolean, fiatError: string, cryptoPrices: any, cryptoSuccess: boolean, cryptoError: string };
}

interface ILoginRequest {
    username: string | null;
    password: string | null;
}


/**
* SQL file: ../../npgsqlrest-docs/examples/9_http_calls_sql_file/sql/financial-dashboard.sql
* 
* @remarks
* HTTP GET /financial-dashboard
* @authorize
* @param $1 _base_currency text
* @param $2 _target_currencies_csv text
* @param $3 _crypto_ids_csv text
* @param $4 _vs_currencies_csv text
* @param $5 _exchange_rate_response example_9.exchange_rate_api
* @param $6 _crypto_response example_9.crypto_price_api
*  @skip
*  @result dashboard
*  @single
*  @returns example_9.financial_dashboard_result
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IFinancialDashboardResponse>}
*/
export async function financialDashboard(
    request: IFinancialDashboardRequest
) : Promise<ApiResult<IFinancialDashboardResponse>> {
    const response = await fetch(baseUrl + "/financial-dashboard" + parseQuery(request), {
        method: "GET",
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IFinancialDashboardResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/9_http_calls_sql_file/sql/login.sql
* 
* @remarks
* HTTP POST
* @login
* @allow_anonymous
* @param $1 username
* @param $2 password
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<string>}
*/
export async function login(
    request: ILoginRequest
) : Promise<ApiResult<string>> {
    const response = await fetch(baseUrl + "/api/login", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/9_http_calls_sql_file/sql/logout.sql
* 
* @remarks
*  HTTP POST
*  @logout
*  @authorize
* 
* @returns {status: number, error: ApiError | undefined}
*/
export async function logout() : Promise<{status: number, error: ApiError | undefined}> {
    const response = await fetch(baseUrl + "/api/logout", {
        method: "POST",
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

