// autogenerated at 2026-06-26T14:54:46.9899880+02:00


const baseUrl = "";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

interface IAverageBookPriceResponse {
    avgPrice: number | null;
}


/**
* function example_18.average_book_price(
*     _response_body text DEFAULT NULL::example_18.books_api,
*     _response_status_code integer,
*     _response_success boolean,
*     _response_error_message text
* )
* returns table(
*     avg_price numeric
* )
* 
* @remarks
* comment on function example_18.average_book_price is 'HTTP POST /average-book-price
* body_parameter_name _response_body
* allow_anonymous
* single
* proxy';
* 
* @returns {ApiResult<IAverageBookPriceResponse>}
* 
* @see FUNCTION example_18.average_book_price
*/
export async function averageBookPrice() : Promise<ApiResult<IAverageBookPriceResponse>> {
    const response = await fetch(baseUrl + "/average-book-price", {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IAverageBookPriceResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

