// autogenerated at 2026-04-01T10:42:21.0764790+02:00


const baseUrl = "";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

interface IGetMyUploadsRequest {
    _user_id?: string | null;
}

interface IGetMyUploadsResponse {
    id: number | null;
    userId: number | null;
    fileName: string | null;
    contentType: string | null;
    fileSize: number | null;
    oid: number | null;
    filePath: string | null;
    uploadedAt: string | null;
}

interface ILoginRequest {
    username: string | null;
    password: string | null;
}

interface IUploadToCombinedRequest {
    _user_id?: string | null;
    _meta?: string | null;
}

interface IUploadToCombinedResponse {
    type: string;
    fileName: string;
    contentType: string;
    size: number;
    success: boolean;
    status: string;
    [key: string]: string | number | boolean;
}

interface IUploadToFileSystemRequest {
    _user_id?: string | null;
    _meta?: string | null;
}

interface IUploadToFileSystemResponse {
    type: string;
    fileName: string;
    contentType: string;
    size: number;
    success: boolean;
    status: string;
    [key: string]: string | number | boolean;
}

interface IUploadToLargeObjectRequest {
    _user_id?: string | null;
    _meta?: string | null;
}

interface IUploadToLargeObjectResponse {
    type: string;
    fileName: string;
    contentType: string;
    size: number;
    success: boolean;
    status: string;
    [key: string]: string | number | boolean;
}


/**
* SQL file: ./6_image_uploads_sql_file/sql/get-my-uploads.sql
* 
* @remarks
* HTTP GET
* @authorize
* @user_parameters
* @param $1 _user_id text = null
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IGetMyUploadsResponse[]>}
* 
* @see SQLFILE public.get-my-uploads
*/
export async function getMyUploads(
    request: IGetMyUploadsRequest
) : Promise<ApiResult<IGetMyUploadsResponse[]>> {
    const response = await fetch(baseUrl + "/api/get-my-uploads" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetMyUploadsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ./6_image_uploads_sql_file/sql/login.sql
* 
* @remarks
* HTTP POST
* @login
* @@anonymous
* @param $1 username
* @param $2 password
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<string>}
* 
* @see SQLFILE public.login
*/
export async function login(
    request: ILoginRequest
) : Promise<ApiResult<string>> {
    const response = await fetch(baseUrl + "/api/login", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ./6_image_uploads_sql_file/sql/logout.sql
* 
* @remarks
*  HTTP POST
*  @logout
*  @authorize
* 
* @returns {status: number, error: ApiError | undefined}
* 
* @see SQLFILE public.logout
*/
export async function logout() : Promise<{status: number, error: ApiError | undefined}> {
    const response = await fetch(baseUrl + "/api/logout", {
        method: "POST",
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ./6_image_uploads_sql_file/sql/upload-to-combined.sql
* 
* @remarks
* HTTP POST
* @upload for large_object, file_system
* @param $1 _user_id text = null
* @param $2 _meta json = null
* @param _meta is upload metadata
* @check_image = true
* @path = ./6_image_uploads_sql_file/public/uploads
* @unique_name = true
* @create_path = true
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IUploadToCombinedResponse[]>}
* 
* @see SQLFILE public.upload-to-combined
*/
export async function uploadToCombined(
    files: FileList | null,
    request: IUploadToCombinedRequest,
    progress?: (loaded: number, total: number) => void,
): Promise<ApiResult<IUploadToCombinedResponse[]>> {
    return new Promise((resolve, reject) => {
        if (!files || files.length === 0) {
            reject(new Error("No files to upload"));
            return;
        }
        var xhr = new XMLHttpRequest();
        if (progress) {
            xhr.upload.addEventListener(
                "progress",
                (event) => {
                    if (event.lengthComputable && progress) {
                        progress(event.loaded, event.total);
                    }
                },
                false
            );
        }
        xhr.onload = function () {
            if (this.status >= 200 && this.status < 300) {
                resolve({status: this.status, response: JSON.parse(this.responseText) as IUploadToCombinedResponse[], error: undefined});
            } else {
                resolve({status: this.status, response: [], error: JSON.parse(this.responseText) as ApiError});
            }
        };
        xhr.onerror = function () {
            reject({
                xhr: this, 
                status: this.status,
                statusText: this.statusText || 'Network error occurred',
                response: this.response
            });
        };
        xhr.open("POST", baseUrl + "/api/upload-to-combined" + parseQuery(request));
        const formData = new FormData();
        for(let i = 0; i < files.length; i++) {
            const file = files[i];
            formData.append("file", file, file.name);
        }
        xhr.send(formData);
    });
}

/**
* SQL file: ./6_image_uploads_sql_file/sql/upload-to-file-system.sql
* 
* @remarks
* HTTP POST
* @upload for file_system
* @param $1 _user_id text = null
* @param $2 _meta json = null
* @param _meta is upload metadata
* @check_image = true
* @path = ./6_image_uploads_sql_file/public/uploads
* @unique_name = true
* @create_path = true
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IUploadToFileSystemResponse[]>}
* 
* @see SQLFILE public.upload-to-file-system
*/
export async function uploadToFileSystem(
    files: FileList | null,
    request: IUploadToFileSystemRequest,
    progress?: (loaded: number, total: number) => void,
): Promise<ApiResult<IUploadToFileSystemResponse[]>> {
    return new Promise((resolve, reject) => {
        if (!files || files.length === 0) {
            reject(new Error("No files to upload"));
            return;
        }
        var xhr = new XMLHttpRequest();
        if (progress) {
            xhr.upload.addEventListener(
                "progress",
                (event) => {
                    if (event.lengthComputable && progress) {
                        progress(event.loaded, event.total);
                    }
                },
                false
            );
        }
        xhr.onload = function () {
            if (this.status >= 200 && this.status < 300) {
                resolve({status: this.status, response: JSON.parse(this.responseText) as IUploadToFileSystemResponse[], error: undefined});
            } else {
                resolve({status: this.status, response: [], error: JSON.parse(this.responseText) as ApiError});
            }
        };
        xhr.onerror = function () {
            reject({
                xhr: this, 
                status: this.status,
                statusText: this.statusText || 'Network error occurred',
                response: this.response
            });
        };
        xhr.open("POST", baseUrl + "/api/upload-to-file-system" + parseQuery(request));
        const formData = new FormData();
        for(let i = 0; i < files.length; i++) {
            const file = files[i];
            formData.append("file", file, file.name);
        }
        xhr.send(formData);
    });
}

/**
* SQL file: ./6_image_uploads_sql_file/sql/upload-to-large-object.sql
* 
* @remarks
* HTTP POST
* @upload for large_object
* @param $1 _user_id text = null
* @param $2 _meta json = null
* @param _meta is upload metadata
* @check_image = true
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IUploadToLargeObjectResponse[]>}
* 
* @see SQLFILE public.upload-to-large-object
*/
export async function uploadToLargeObject(
    files: FileList | null,
    request: IUploadToLargeObjectRequest,
    progress?: (loaded: number, total: number) => void,
): Promise<ApiResult<IUploadToLargeObjectResponse[]>> {
    return new Promise((resolve, reject) => {
        if (!files || files.length === 0) {
            reject(new Error("No files to upload"));
            return;
        }
        var xhr = new XMLHttpRequest();
        if (progress) {
            xhr.upload.addEventListener(
                "progress",
                (event) => {
                    if (event.lengthComputable && progress) {
                        progress(event.loaded, event.total);
                    }
                },
                false
            );
        }
        xhr.onload = function () {
            if (this.status >= 200 && this.status < 300) {
                resolve({status: this.status, response: JSON.parse(this.responseText) as IUploadToLargeObjectResponse[], error: undefined});
            } else {
                resolve({status: this.status, response: [], error: JSON.parse(this.responseText) as ApiError});
            }
        };
        xhr.onerror = function () {
            reject({
                xhr: this, 
                status: this.status,
                statusText: this.statusText || 'Network error occurred',
                response: this.response
            });
        };
        xhr.open("POST", baseUrl + "/api/upload-to-large-object" + parseQuery(request));
        const formData = new FormData();
        for(let i = 0; i < files.length; i++) {
            const file = files[i];
            formData.append("file", file, file.name);
        }
        xhr.send(formData);
    });
}

