<template>
  <CodeTerminal
    :frames="frames"
    aria-label="A PostgreSQL function turning into a REST endpoint and typed TypeScript client"
  />
</template>

<script setup>
import CodeTerminal from './CodeTerminal.vue'

const frames = [
  {
    title: '~ sql/get_users.sql',
    blocks: [
      {
        command: 'cat sql/get_users.sql',
        lines: [
          { text: 'create or replace function api.get_users(', cls: 'sql' },
          { text: '    _department_id int', cls: 'sql' },
          { text: ')', cls: 'sql' },
          { text: 'returns table (id int, name text, email text, role text)', cls: 'sql' },
          { text: 'language sql', cls: 'sql' },
          { text: 'begin atomic;', cls: 'sql' },
          { text: 'select id, name, email, role from users', cls: 'sql' },
          { text: 'where _department_id is null or department_id = _department_id;', cls: 'sql' },
          { text: 'end;', cls: 'sql' },
          { text: '', cls: 'sql' },
          { text: "comment on function api.get_users(int) is '", cls: 'sql' },
          { text: 'HTTP GET /users/', cls: 'comment' },
          { text: '@authorize admin, user', cls: 'comment' },
          { text: '@cached', cls: 'comment' },
          { text: '@cache_expires_in 30sec', cls: 'comment' },
          { text: '@timeout 10sec', cls: 'comment' },
          { text: '@retry_strategy aggressive', cls: 'comment' },
          { text: '@rate_limiter_policy authenticated_limit', cls: 'comment' },
          { text: '@tsclient_module = users', cls: 'comment' },
          { text: "';", cls: 'sql' }
        ]
      },
      {
        command: "curl -s 'localhost:8080/users/?_department_id=1' | jq",
        lineMs: 75,
        lines: [
          { text: '[', cls: 'punct' },
          { text: '  { "id": 1, "name": "Alice", "email": "alice@acme.io", "role": "admin" },', cls: 'json' },
          { text: '  { "id": 4, "name": "Diana", "email": "diana@acme.io", "role": "admin" },', cls: 'json' },
          { text: '  { "id": 7, "name": "Eve",   "email": "eve@acme.io",   "role": "user"  }', cls: 'json' },
          { text: ']', cls: 'punct' }
        ]
      }
    ]
  },
  {
    title: '~ src/users.ts',
    blocks: [
      {
        command: 'cat src/users.ts',
        lineMs: 45,
        lines: [
          { text: '// autogenerated at 2026-05-11T10:23:00+00:00', cls: 'comment' },
          { text: '', cls: 'ts' },
          { text: 'interface IGetUsersRequest {', cls: 'ts' },
          { text: '    _department_id?: number | null;', cls: 'ts' },
          { text: '}', cls: 'ts' },
          { text: '', cls: 'ts' },
          { text: 'interface IGetUsersResponse {', cls: 'ts' },
          { text: '    id: number | null;', cls: 'ts' },
          { text: '    name: string | null;', cls: 'ts' },
          { text: '    email: string | null;', cls: 'ts' },
          { text: '    role: string | null;', cls: 'ts' },
          { text: '}', cls: 'ts' },
          { text: '', cls: 'ts' },
          { text: 'export async function getUsers(', cls: 'ts' },
          { text: '    request: IGetUsersRequest', cls: 'ts' },
          { text: ') : Promise<ApiResult<IGetUsersResponse[]>> {', cls: 'ts' },
          { text: '    const response = await fetch(baseUrl + "/users/" + parseQuery(request), {', cls: 'ts' },
          { text: '        method: "GET",', cls: 'ts' },
          { text: '        headers: { "Content-Type": "application/json" },', cls: 'ts' },
          { text: '    });', cls: 'ts' },
          { text: '    return {', cls: 'ts' },
          { text: '        status: response.status,', cls: 'ts' },
          { text: '        response: response.ok ? await response.json() as IGetUsersResponse[] : undefined!,', cls: 'ts' },
          { text: '        error: !response.ok ? await response.json() as ApiError : undefined', cls: 'ts' },
          { text: '    };', cls: 'ts' },
          { text: '}', cls: 'ts' }
        ]
      }
    ]
  }
]
</script>
