<template>
  <CodeTerminal
    :frames="frames"
    aria-label="SQL file declarations turning into a REST endpoint and typed TypeScript client"
  />
</template>

<script setup>
import CodeTerminal from './CodeTerminal.vue'

const frames = [
  {
    title: '~ sql/users.sql',
    blocks: [
      {
        command: 'cat sql/users.sql',
        lines: [
          { text: '/*', cls: 'comment' },
          { text: 'HTTP GET /users/', cls: 'comment' },
          { text: '@authorize admin, user', cls: 'comment' },
          { text: '@cached', cls: 'comment' },
          { text: '@cache_expires_in 30sec', cls: 'comment' },
          { text: '@timeout 5min', cls: 'comment' },
          { text: '@param $1 department_id text', cls: 'comment' },
          { text: '*/', cls: 'comment' },
          { text: 'select id, name, email, role', cls: 'sql' },
          { text: 'from users', cls: 'sql' },
          { text: 'where $1 is null or department_id = $1;', cls: 'sql' }
        ]
      },
      {
        command: "curl -s 'localhost:8080/users/?department_id=1' | jq",
        lineMs: 75,
        lines: [
          { text: '[', cls: 'punct' },
          { text: '  { "id": 1, "name": "Alice", "email": "alice@acme.io", "role": "admin" },', cls: 'json' },
          { text: '  { "id": 4, "name": "Diana", "email": "diana@acme.io", "role": "admin" },', cls: 'json' },
          { text: '  { "id": 7, "name": "Eve",   "email": "eve@acme.io",   "role": "user"  }', cls: 'json' },
          { text: ']', cls: 'punct' }
        ]
      }
    ]
  },
  {
    title: '~ src/sqlApi.ts',
    blocks: [
      {
        command: 'cat src/sqlApi.ts',
        lineMs: 45,
        lines: [
          { text: '// autogenerated at 2026-05-11T10:23:00+00:00', cls: 'comment' },
          { text: '', cls: 'ts' },
          { text: 'interface IUsersRequest {', cls: 'ts' },
          { text: '    department_id?: string | null;', cls: 'ts' },
          { text: '}', cls: 'ts' },
          { text: '', cls: 'ts' },
          { text: 'interface IUsersResponse {', cls: 'ts' },
          { text: '    id: number | null;', cls: 'ts' },
          { text: '    name: string | null;', cls: 'ts' },
          { text: '    email: string | null;', cls: 'ts' },
          { text: '    role: string | null;', cls: 'ts' },
          { text: '}', cls: 'ts' },
          { text: '', cls: 'ts' },
          { text: 'export async function users(', cls: 'ts' },
          { text: '    request: IUsersRequest', cls: 'ts' },
          { text: ') : Promise<ApiResult<IUsersResponse[]>> {', cls: 'ts' },
          { text: '    const response = await fetch(baseUrl + "/users/" + parseQuery(request), {', cls: 'ts' },
          { text: '        method: "GET",', cls: 'ts' },
          { text: '        headers: { "Content-Type": "application/json" },', cls: 'ts' },
          { text: '    });', cls: 'ts' },
          { text: '    return {', cls: 'ts' },
          { text: '        status: response.status,', cls: 'ts' },
          { text: '        response: response.ok ? await response.json() as IUsersResponse[] : undefined!,', cls: 'ts' },
          { text: '        error: !response.ok ? await response.json() as ApiError : undefined', cls: 'ts' },
          { text: '    };', cls: 'ts' },
          { text: '}', cls: 'ts' }
        ]
      }
    ]
  }
]
</script>
