// autogenerated at 2026-03-28T13:30:40.1624910+01:00
const baseUrl = "";

interface IGetPostsResponse {
    username: string | null;
    content: string | null;
    createdAt: string | null;
}

interface IGetUsersResponse {
    userId: number | null;
    username: string | null;
    email: string | null;
    active: boolean | null;
}


/**
* SQL file: ../../npgsqlrest-docs/examples/2_static_type_checking_sql_file/sql_2/get-posts.sql
* 
* @remarks
*  HTTP GET
* 
* @returns {status: number, response: IGetPostsResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see SQLFILE public.get-posts
*/
export async function getPosts() : Promise<{status: number, response: IGetPostsResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/get-posts", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetPostsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/2_static_type_checking_sql_file/sql_2/get-users.sql
* 
* @remarks
*  HTTP GET
* 
* @returns {status: number, response: IGetUsersResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see SQLFILE public.get-users
*/
export async function getUsers() : Promise<{status: number, response: IGetUsersResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/get-users", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetUsersResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

