// autogenerated at 2026-03-31T18:47:10.9822970+02:00


const baseUrl = "";

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

interface IGetPostsResponse {
    username: string | null;
    content: string | null;
    createdAt: string | null;
}

interface IGetUsersResponse {
    userId: number | null;
    username: string | null;
    email: string | null;
    active: boolean | null;
}


/**
* SQL file: ../../npgsqlrest-docs/examples/2_static_type_checking_sql_file/sql/get-posts.sql
* 
* @remarks
*  HTTP GET
* 
* @returns {ApiResult<IGetPostsResponse[]>}
* 
* @see SQLFILE public.get-posts
*/
export async function getPosts() : Promise<ApiResult<IGetPostsResponse[]>> {
    const response = await fetch(baseUrl + "/api/get-posts", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetPostsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/2_static_type_checking_sql_file/sql/get-users.sql
* 
* @remarks
*  HTTP GET
* 
* @returns {ApiResult<IGetUsersResponse[]>}
* 
* @see SQLFILE public.get-users
*/
export async function getUsers() : Promise<ApiResult<IGetUsersResponse[]>> {
    const response = await fetch(baseUrl + "/api/get-users", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetUsersResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

