// autogenerated at 2026-04-02T11:57:21.3966680+02:00


const baseUrl = "";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

interface IAiAnalyzeRequest {
    text: string | null;
    maxLength?: number | null;
    maxKeywords?: number | null;
    _proxy_status_code?: number | null;
    _proxy_body?: string | null;
    _proxy_success?: boolean | null;
    _proxy_error_message?: string | null;
}

interface IAiAnalyzeResponse {
    result: any;
}

interface IAiSentimentRequest {
    text: string | null;
    _proxy_status_code?: number | null;
    _proxy_body?: string | null;
    _proxy_success?: boolean | null;
    _proxy_error_message?: string | null;
}

interface IAiSentimentResponse {
    result: any;
}

interface IAiSummarizeRequest {
    text: string | null;
    maxLength?: number | null;
    _proxy_status_code?: number | null;
    _proxy_body?: string | null;
    _proxy_success?: boolean | null;
    _proxy_error_message?: string | null;
}

interface IAiSummarizeResponse {
    result: any;
}

interface ICacheEntriesRequest {
    _limit?: number | null;
}

interface ICacheEntriesResponse {
    id: number | null;
    textPreview: string | null;
    hasSummary: boolean | null;
    sentiment: string | null;
    keywords: string[] | null;
    accessedCount: number | null;
    createdAt: string | null;
}

interface ICacheStatsResponse {
    totalCached: number | null;
    totalCacheHits: number | null;
    mostAccessedPreview: string | null;
    mostAccessedHits: number | null;
    oldestEntry: string | null;
    newestEntry: string | null;
}

interface ILoginRequest {
    username: string | null;
    password: string | null;
}


/**
* SQL file: ../../npgsqlrest-docs/examples/10_proxy_ai_service_sql_file/sql/ai-analyze.sql
* 
* @remarks
* HTTP POST /ai/analyze
* authorize
* proxy POST
* param $1 text text
* param $2 maxLength int default 150
* param $3 maxKeywords int default 5
* param $4 _proxy_status_code int default null
* param $5 _proxy_body text default null
* param $6 _proxy_success boolean default null
* param $7 _proxy_error_message text default null
*  skip
*  returns json
*  single
*  result result
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IAiAnalyzeResponse>}
*/
export async function aiAnalyze(
    request: IAiAnalyzeRequest
) : Promise<ApiResult<IAiAnalyzeResponse>> {
    const response = await fetch(baseUrl + "/ai/analyze", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IAiAnalyzeResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/10_proxy_ai_service_sql_file/sql/ai-health.sql
* 
* @remarks
*  HTTP GET /ai/health
*  proxy
*  void
* 
* @returns {ApiResult<string[]>}
*/
export async function aiHealth() : Promise<ApiResult<string[]>> {
    const response = await fetch(baseUrl + "/ai/health", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as string[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/10_proxy_ai_service_sql_file/sql/ai-sentiment.sql
* 
* @remarks
* HTTP POST /ai/sentiment
* authorize
* proxy POST
* param $1 text text
* param $2 _proxy_status_code int default null
* param $3 _proxy_body text default null
* param $4 _proxy_success boolean default null
* param $5 _proxy_error_message text default null
*  skip
*  returns json
*  single
*  result result
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IAiSentimentResponse>}
*/
export async function aiSentiment(
    request: IAiSentimentRequest
) : Promise<ApiResult<IAiSentimentResponse>> {
    const response = await fetch(baseUrl + "/ai/sentiment", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IAiSentimentResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/10_proxy_ai_service_sql_file/sql/ai-summarize.sql
* 
* @remarks
* HTTP POST /ai/summarize
* authorize
* proxy POST
* param $1 text text
* param $2 maxLength int default 150
* param $3 _proxy_status_code int default null
* param $4 _proxy_body text default null
* param $5 _proxy_success boolean default null
* param $6 _proxy_error_message text default null
*  skip
*  returns json
*  single
*  result result
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IAiSummarizeResponse>}
*/
export async function aiSummarize(
    request: IAiSummarizeRequest
) : Promise<ApiResult<IAiSummarizeResponse>> {
    const response = await fetch(baseUrl + "/ai/summarize", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IAiSummarizeResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/10_proxy_ai_service_sql_file/sql/cache-clear.sql
* 
* @remarks
* HTTP DELETE /cache/clear
* authorize
* single
* 
* @returns {ApiResult<any>}
*/
export async function cacheClear() : Promise<ApiResult<any>> {
    const response = await fetch(baseUrl + "/cache/clear", {
        method: "DELETE",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as any : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/10_proxy_ai_service_sql_file/sql/cache-entries.sql
* 
* @remarks
* HTTP GET /cache/entries
* authorize
* param $1 _limit int default 10
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<ICacheEntriesResponse[]>}
*/
export async function cacheEntries(
    request: ICacheEntriesRequest
) : Promise<ApiResult<ICacheEntriesResponse[]>> {
    const response = await fetch(baseUrl + "/cache/entries" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as ICacheEntriesResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/10_proxy_ai_service_sql_file/sql/cache-stats.sql
* 
* @remarks
* HTTP GET /cache/stats
* authorize
* 
* @returns {ApiResult<ICacheStatsResponse[]>}
*/
export async function cacheStats() : Promise<ApiResult<ICacheStatsResponse[]>> {
    const response = await fetch(baseUrl + "/cache/stats", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as ICacheStatsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/10_proxy_ai_service_sql_file/sql/login.sql
* 
* @remarks
* HTTP POST
* login
* allow_anonymous
* param $1 username
* param $2 password
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<string>}
*/
export async function login(
    request: ILoginRequest
) : Promise<ApiResult<string>> {
    const response = await fetch(baseUrl + "/api/login", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/10_proxy_ai_service_sql_file/sql/logout.sql
* 
* @remarks
*  HTTP POST
*  logout
*  authorize
* 
* @returns {status: number, error: ApiError | undefined}
*/
export async function logout() : Promise<{status: number, error: ApiError | undefined}> {
    const response = await fetch(baseUrl + "/api/logout", {
        method: "POST",
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

