// autogenerated at 2026-07-08T13:04:53.3323340+02:00

import 'dart:convert';
import 'package:http/http.dart' as http;

String baseUrl = '';

/// Override to inject a custom [http.Client] (e.g. MockClient in tests).
http.Client? httpClient;

http.Client get _client => httpClient ??= http.Client();

Future<http.Response> _send(
  String method,
  Uri uri, {
  Map<String, String>? headers,
  String? body,
}) async {
  final request = http.Request(method, uri);
  if (headers != null) {
    request.headers.addAll(headers);
  }
  if (body != null) {
    request.body = body;
  }
  return http.Response.fromStream(await _client.send(request));
}

String _query(Map<String, Object?> query) {
  final parts = <String>[];
  query.forEach((key, value) {
    if (value is List) {
      for (final v in value) {
        parts.add(v == null ? '$key=' : '$key=${Uri.encodeQueryComponent(_str(v))}');
      }
    } else if (value == null) {
      parts.add('$key=');
    } else {
      parts.add('$key=${Uri.encodeQueryComponent(_str(value))}');
    }
  });
  return '?${parts.join('&')}';
}

String _str(Object value) =>
    value is DateTime ? value.toIso8601String() : value.toString();

ApiError? _error(http.Response response) {
  if (response.statusCode >= 200 && response.statusCode < 300) {
    return null;
  }
  if (response.headers['content-length'] == '0') {
    return null;
  }
  return ApiError.fromJson(
    jsonDecode(utf8.decode(response.bodyBytes)) as Map<String, dynamic>,
  );
}

class ApiError {
  final int? status;
  final String? title;
  final String? detail;

  const ApiError({this.status, this.title, this.detail});

  factory ApiError.fromJson(Map<String, dynamic> json) {
    return ApiError(
      status: (json['status'] as num?)?.toInt(),
      title: json['title'] as String?,
      detail: json['detail'] as String?,
    );
  }
}

class ApiResult<T> {
  final int status;
  final T? response;
  final ApiError? error;

  const ApiResult({required this.status, this.response, this.error});

  bool get ok => status >= 200 && status < 300;
}

class Example22CreateOrderRequest {
  final int? productId;
  final int? quantity;
  final String? note;

  const Example22CreateOrderRequest({
    this.productId,
    this.quantity,
    this.note,
  });

  factory Example22CreateOrderRequest.fromJson(Map<String, dynamic> json) {
    return Example22CreateOrderRequest(
      productId: (json['productId'] as num?)?.toInt(),
      quantity: (json['quantity'] as num?)?.toInt(),
      note: json['note'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'productId': productId,
      'quantity': quantity,
      if (note != null) 'note': note,
    };
  }
}

class ProductsIdRequest {
  final int? id;

  const ProductsIdRequest({
    this.id,
  });

  factory ProductsIdRequest.fromJson(Map<String, dynamic> json) {
    return ProductsIdRequest(
      id: (json['id'] as num?)?.toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
    };
  }
}

class ProductsIdResponse {
  final int? id;
  final String? name;
  final double? price;

  const ProductsIdResponse({
    this.id,
    this.name,
    this.price,
  });

  factory ProductsIdResponse.fromJson(Map<String, dynamic> json) {
    return ProductsIdResponse(
      id: (json['id'] as num?)?.toInt(),
      name: json['name'] as String?,
      price: (json['price'] as num?)?.toDouble(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'price': price,
    };
  }
}

class Example22SearchProductsRequest {
  final String? search;
  final int? page;
  final int? limit;

  const Example22SearchProductsRequest({
    this.search,
    this.page,
    this.limit,
  });

  factory Example22SearchProductsRequest.fromJson(Map<String, dynamic> json) {
    return Example22SearchProductsRequest(
      search: json['search'] as String?,
      page: (json['page'] as num?)?.toInt(),
      limit: (json['limit'] as num?)?.toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'search': search,
      'page': page,
      if (limit != null) 'limit': limit,
    };
  }
}

class Example22SearchProductsResponse {
  final int? id;
  final String? name;
  final double? price;
  final DateTime? createdAt;

  const Example22SearchProductsResponse({
    this.id,
    this.name,
    this.price,
    this.createdAt,
  });

  factory Example22SearchProductsResponse.fromJson(Map<String, dynamic> json) {
    return Example22SearchProductsResponse(
      id: (json['id'] as num?)?.toInt(),
      name: json['name'] as String?,
      price: (json['price'] as num?)?.toDouble(),
      createdAt: json['createdAt'] == null ? null : DateTime.parse(json['createdAt'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'price': price,
      'createdAt': createdAt?.toIso8601String(),
    };
  }
}

/// function example_22.create_order(
///     _product_id integer,
///     _quantity integer,
///     _note text DEFAULT NULL::text
/// )
/// returns integer
///
/// comment on function example_22.create_order is 'HTTP POST';
///
/// [request] Carries the endpoint parameters.
/// Returns `ApiResult<int>`.
///
/// See FUNCTION example_22.create_order
Future<ApiResult<int>> example22CreateOrder(Example22CreateOrderRequest request) async {
  final uri = Uri.parse('$baseUrl/api/example-22/create-order');
  final response = await _send(
    'POST',
    uri,
    body: jsonEncode(request.toJson()),
  );
  final ok = response.statusCode >= 200 && response.statusCode < 300;
  return ApiResult<int>(
    status: response.statusCode,
    response: ok ? int.parse(utf8.decode(response.bodyBytes)) : null,
    error: _error(response),
  );
}

/// function example_22.get_product(
///     _id integer
/// )
/// returns table(
///     id integer,
///     name text,
///     price numeric
/// )
///
/// comment on function example_22.get_product is 'HTTP GET
/// path /api/products/{_id}
/// single';
///
/// [request] Carries the endpoint parameters.
/// Returns `ApiResult<ProductsIdResponse>`.
///
/// See FUNCTION example_22.get_product
Future<ApiResult<ProductsIdResponse>> productsId(ProductsIdRequest request) async {
  final uri = Uri.parse('$baseUrl/api/products/${request.id}');
  final response = await _send(
    'GET',
    uri,
    headers: {
      'Content-Type': 'application/json',
    },
  );
  final ok = response.statusCode >= 200 && response.statusCode < 300;
  return ApiResult<ProductsIdResponse>(
    status: response.statusCode,
    response: ok ? ProductsIdResponse.fromJson(jsonDecode(utf8.decode(response.bodyBytes)) as Map<String, dynamic>) : null,
    error: _error(response),
  );
}

/// function example_22.search_products(
///     _search text,
///     _page integer,
///     _limit integer DEFAULT 10
/// )
/// returns table(
///     id integer,
///     name text,
///     price numeric,
///     created_at timestamp without time zone
/// )
///
/// comment on function example_22.search_products is 'HTTP GET
/// request_param_type query_string
/// dartclient_status_code=true';
///
/// [request] Carries the endpoint parameters.
/// Returns `ApiResult<List<Example22SearchProductsResponse>>`.
///
/// See FUNCTION example_22.search_products
Future<ApiResult<List<Example22SearchProductsResponse>>> example22SearchProducts(Example22SearchProductsRequest request) async {
  final uri = Uri.parse('$baseUrl/api/example-22/search-products' + _query({
    'search': request.search,
    'page': request.page,
    if (request.limit != null) 'limit': request.limit,
  }));
  final response = await _send(
    'GET',
    uri,
    headers: {
      'Content-Type': 'application/json',
    },
  );
  final ok = response.statusCode >= 200 && response.statusCode < 300;
  return ApiResult<List<Example22SearchProductsResponse>>(
    status: response.statusCode,
    response: ok
        ? (jsonDecode(utf8.decode(response.bodyBytes)) as List)
            .map((e) => Example22SearchProductsResponse.fromJson(e as Map<String, dynamic>))
            .toList()
        : null,
    error: _error(response),
  );
}
