// autogenerated at 2026-04-02T13:27:38.8123000+02:00


const baseUrl = "";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

export const getDataUrl = (request: IGetDataRequest) => baseUrl + "/api/get-data" + parseQuery(request);

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

interface IGetDataRequest {
    format?: string | null;
    excelFileName?: string | null;
    excelSheet?: string | null;
}

interface ILoginRequest {
    username: string | null;
    password: string | null;
}



/**
* SQL file: ../../npgsqlrest-docs/examples/14_table_format_sql_file/sql/login.sql
* 
* @remarks
* HTTP POST
* login
* allow_anonymous
* param $1 username
* param $2 password
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<string>}
*/
export async function login(
    request: ILoginRequest
) : Promise<ApiResult<string>> {
    const response = await fetch(baseUrl + "/api/login", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/14_table_format_sql_file/sql/logout.sql
* 
* @remarks
*  HTTP POST
*  logout
*  authorize
* 
* @returns {status: number, error: ApiError | undefined}
*/
export async function logout() : Promise<{status: number, error: ApiError | undefined}> {
    const response = await fetch(baseUrl + "/api/logout", {
        method: "POST",
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

