// autogenerated at 2026-01-03T11:47:52.4474660+01:00


const baseUrl = "http://127.0.0.1:8080";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

interface ILoginRequest {
    username: string | null;
    password: string | null;
}

interface IWhoAmIRequest {
    userId?: string | null;
    username?: string | null;
    email?: string | null;
}

interface IWhoAmIResponse {
    userId: string | null;
    username: string | null;
    email: string | null;
}


/**
* function example_3_public.login(
*     _username text,
*     _password text
* )
* returns table(
*     scheme text,
*     user_id integer,
*     username text,
*     email text
* )
* 
* @remarks
* comment on function example_3_public.login is 'HTTP POST
* login
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_3_public.login
*/
export async function login(
    request: ILoginRequest
) : Promise<{status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-3-public/login", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_3_public.logout()
* returns text
* 
* @remarks
* comment on function example_3_public.logout is 'HTTP POST
* logout
* authorize';
* 
* @returns {status: number, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_3_public.logout
*/
export async function logout() : Promise<{status: number, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-3-public/logout", {
        method: "POST",
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_3_public.who_am_i(
*     _user_id text DEFAULT NULL::text,
*     _username text DEFAULT NULL::text,
*     _email text DEFAULT NULL::text
* )
* returns table(
*     user_id text,
*     username text,
*     email text
* )
* 
* @remarks
* comment on function example_3_public.who_am_i is 'HTTP GET
* authorize';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IWhoAmIResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_3_public.who_am_i
*/
export async function whoAmI(
    request: IWhoAmIRequest
) : Promise<{status: number, response: IWhoAmIResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-3-public/who-am-i" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IWhoAmIResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

