// autogenerated at 2026-01-07T12:30:57.4064030+01:00


const baseUrl = "http://127.0.0.1:8080";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

interface IContactsGetRequest {
    id?: number | null;
    name?: string | null;
    email?: string | null;
    phone?: string | null;
    createdAt?: string | null;
}

interface IContactsGetResponse {
    id: number | null;
    name: string | null;
    email: string | null;
    phone: string | null;
    createdAt: string | null;
}

interface IContactsPostRequest {
    id?: number | null;
    name?: string | null;
    email?: string | null;
    phone?: string | null;
    createdAt?: string | null;
}

interface IContactsPost1Request {
    id?: number | null;
    name?: string | null;
    email?: string | null;
    phone?: string | null;
    createdAt?: string | null;
}

interface IContactsPost1Response {
    id: number | null;
    name: string | null;
    email: string | null;
    phone: string | null;
    createdAt: string | null;
}

interface IContactsDeleteRequest {
    id?: number | null;
    name?: string | null;
    email?: string | null;
    phone?: string | null;
    createdAt?: string | null;
}

interface IContactsDelete1Request {
    id?: number | null;
    name?: string | null;
    email?: string | null;
    phone?: string | null;
    createdAt?: string | null;
}

interface IContactsDelete1Response {
    id: number | null;
    name: string | null;
    email: string | null;
    phone: string | null;
    createdAt: string | null;
}

interface IContactsPutRequest {
    id?: number | null;
    name?: string | null;
    email?: string | null;
    phone?: string | null;
    createdAt?: string | null;
}

interface IContactsPutResponse {
    id: number | null;
    name: string | null;
    email: string | null;
    phone: string | null;
    createdAt: string | null;
}

interface ILoginRequest {
    username: string | null;
    password: string | null;
}


/**
* select example_11.contacts
* 
* @remarks
* comment on function example_11.contacts is 'HTTP
* disabled
* enabled select, insert_returning, update, delete';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IContactsGetResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see TABLE example_11.contacts
*/
export async function contactsGet(
    request: IContactsGetRequest
) : Promise<{status: number, response: IContactsGetResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-11/contacts" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IContactsGetResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* update example_11.contacts
* 
* @remarks
* comment on function example_11.contacts is 'HTTP
* disabled
* enabled select, insert_returning, update, delete';
* 
* @param request - Object containing request parameters.
* @returns {status: number, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see TABLE example_11.contacts
*/
export async function contactsPost(
    request: IContactsPostRequest
) : Promise<{status: number, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-11/contacts", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* update example_11.contacts
* returning
*     id, name, email, phone, created_at
* 
* @remarks
* comment on function example_11.contacts is 'HTTP
* disabled
* enabled select, insert_returning, update, delete';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IContactsPost1Response[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see TABLE example_11.contacts
*/
export async function contactsPost1(
    request: IContactsPost1Request
) : Promise<{status: number, response: IContactsPost1Response[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-11/contacts/returning", {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IContactsPost1Response[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* delete from example_11.contacts
* 
* @remarks
* comment on function example_11.contacts is 'HTTP
* disabled
* enabled select, insert_returning, update, delete';
* 
* @param request - Object containing request parameters.
* @returns {status: number, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see TABLE example_11.contacts
*/
export async function contactsDelete(
    request: IContactsDeleteRequest
) : Promise<{status: number, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-11/contacts" + parseQuery(request), {
        method: "DELETE",
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* delete from example_11.contacts
* returning
*     id, name, email, phone, created_at
* 
* @remarks
* comment on function example_11.contacts is 'HTTP
* disabled
* enabled select, insert_returning, update, delete';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IContactsDelete1Response[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see TABLE example_11.contacts
*/
export async function contactsDelete1(
    request: IContactsDelete1Request
) : Promise<{status: number, response: IContactsDelete1Response[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-11/contacts/returning" + parseQuery(request), {
        method: "DELETE",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IContactsDelete1Response[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* insert into example_11.contacts
* returning
*     id, name, email, phone, created_at
* 
* @remarks
* comment on function example_11.contacts is 'HTTP
* disabled
* enabled select, insert_returning, update, delete';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IContactsPutResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see TABLE example_11.contacts
*/
export async function contactsPut(
    request: IContactsPutRequest
) : Promise<{status: number, response: IContactsPutResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-11/contacts/returning", {
        method: "PUT",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IContactsPutResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_11.login(
*     _username text,
*     _password text
* )
* returns table(
*     scheme text,
*     user_id integer,
*     user_name text
* )
* 
* @remarks
* comment on function example_11.login is 'HTTP POST
* login
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_11.login
*/
export async function login(
    request: ILoginRequest
) : Promise<{status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-11/login", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_11.logout()
* returns void
* 
* @remarks
* comment on function example_11.logout is 'HTTP POST
* logout';
* 
* @returns {status: number, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_11.logout
*/
export async function logout() : Promise<{status: number, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-11/logout", {
        method: "POST",
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

