// autogenerated at 2026-02-07T10:23:31.0687630+01:00
const baseUrl = "http://127.0.0.1:8080";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

interface ICombinedUploadRequest {
    meta?: string | null;
}

interface ICombinedUploadResponse {
    type: string;
    fileName: string;
    contentType: string;
    size: number;
    success: boolean;
    status: string;
    [key: string]: string | number | boolean;
}

interface ICsvUploadRequest {
    meta?: string | null;
}

interface ICsvUploadResponse {
    type: string;
    fileName: string;
    contentType: string;
    size: number;
    success: boolean;
    status: string;
    [key: string]: string | number | boolean;
}

interface IExcelUploadRequest {
    meta?: string | null;
}

interface IExcelUploadResponse {
    type: string;
    fileName: string;
    contentType: string;
    size: number;
    success: boolean;
    status: string;
    [key: string]: string | number | boolean;
}

interface IGetUploadDataRequest {
    type: string | null;
    userId?: string | null;
}

interface ILoginRequest {
    username: string | null;
    password: string | null;
}


/**
* function example_7.combined_upload(
*     _meta json DEFAULT NULL::json
* )
* returns json
* 
* @remarks
* comment on function example_7.combined_upload is 'HTTP POST
* @authorize
* @upload for excel
* @param _meta is upload metadata
* @all_sheets = true
* @fallback_handler = csv
* @row_command = select example_7.combined_upload_row($1,$2,$3,$4)';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: ICombinedUploadResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_7.combined_upload
*/
export async function combinedUpload(
    files: FileList | null,
    request: ICombinedUploadRequest,
    progress?: (loaded: number, total: number) => void,
): Promise<{status: number, response: ICombinedUploadResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    return new Promise((resolve, reject) => {
        if (!files || files.length === 0) {
            reject(new Error("No files to upload"));
            return;
        }
        var xhr = new XMLHttpRequest();
        if (progress) {
            xhr.upload.addEventListener(
                "progress",
                (event) => {
                    if (event.lengthComputable && progress) {
                        progress(event.loaded, event.total);
                    }
                },
                false
            );
        }
        xhr.onload = function () {
            if (this.status >= 200 && this.status < 300) {
                resolve({status: this.status, response: JSON.parse(this.responseText) as ICombinedUploadResponse[], error: undefined});
            } else {
                resolve({status: this.status, response: [], error: JSON.parse(this.responseText) as {status: number; title: string; detail?: string | null}});
            }
        };
        xhr.onerror = function () {
            reject({
                xhr: this, 
                status: this.status,
                statusText: this.statusText || 'Network error occurred',
                response: this.response
            });
        };
        xhr.open("POST", baseUrl + "/api/example-7/combined-upload" + parseQuery(request));
        const formData = new FormData();
        for(let i = 0; i < files.length; i++) {
            const file = files[i];
            formData.append("file", file, file.name);
        }
        xhr.send(formData);
    });
}

/**
* function example_7.csv_upload(
*     _meta json DEFAULT NULL::json
* )
* returns json
* 
* @remarks
* comment on function example_7.csv_upload is 'HTTP POST
* @authorize
* @upload for csv
* @param _meta is upload metadata
* @delimiters = ,;
* @row_command = select example_7.csv_upload_row($1,$2,$3,$4)';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: ICsvUploadResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_7.csv_upload
*/
export async function csvUpload(
    files: FileList | null,
    request: ICsvUploadRequest,
    progress?: (loaded: number, total: number) => void,
): Promise<{status: number, response: ICsvUploadResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    return new Promise((resolve, reject) => {
        if (!files || files.length === 0) {
            reject(new Error("No files to upload"));
            return;
        }
        var xhr = new XMLHttpRequest();
        if (progress) {
            xhr.upload.addEventListener(
                "progress",
                (event) => {
                    if (event.lengthComputable && progress) {
                        progress(event.loaded, event.total);
                    }
                },
                false
            );
        }
        xhr.onload = function () {
            if (this.status >= 200 && this.status < 300) {
                resolve({status: this.status, response: JSON.parse(this.responseText) as ICsvUploadResponse[], error: undefined});
            } else {
                resolve({status: this.status, response: [], error: JSON.parse(this.responseText) as {status: number; title: string; detail?: string | null}});
            }
        };
        xhr.onerror = function () {
            reject({
                xhr: this, 
                status: this.status,
                statusText: this.statusText || 'Network error occurred',
                response: this.response
            });
        };
        xhr.open("POST", baseUrl + "/api/example-7/csv-upload" + parseQuery(request));
        const formData = new FormData();
        for(let i = 0; i < files.length; i++) {
            const file = files[i];
            formData.append("file", file, file.name);
        }
        xhr.send(formData);
    });
}

/**
* function example_7.excel_upload(
*     _meta json DEFAULT NULL::json
* )
* returns json
* 
* @remarks
* comment on function example_7.excel_upload is 'HTTP POST
* @authorize
* @upload for excel
* @param _meta is upload metadata
* @all_sheets = true
* @row_command = select example_7.excel_upload_row($1,$2,$3,$4)';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IExcelUploadResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_7.excel_upload
*/
export async function excelUpload(
    files: FileList | null,
    request: IExcelUploadRequest,
    progress?: (loaded: number, total: number) => void,
): Promise<{status: number, response: IExcelUploadResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    return new Promise((resolve, reject) => {
        if (!files || files.length === 0) {
            reject(new Error("No files to upload"));
            return;
        }
        var xhr = new XMLHttpRequest();
        if (progress) {
            xhr.upload.addEventListener(
                "progress",
                (event) => {
                    if (event.lengthComputable && progress) {
                        progress(event.loaded, event.total);
                    }
                },
                false
            );
        }
        xhr.onload = function () {
            if (this.status >= 200 && this.status < 300) {
                resolve({status: this.status, response: JSON.parse(this.responseText) as IExcelUploadResponse[], error: undefined});
            } else {
                resolve({status: this.status, response: [], error: JSON.parse(this.responseText) as {status: number; title: string; detail?: string | null}});
            }
        };
        xhr.onerror = function () {
            reject({
                xhr: this, 
                status: this.status,
                statusText: this.statusText || 'Network error occurred',
                response: this.response
            });
        };
        xhr.open("POST", baseUrl + "/api/example-7/excel-upload" + parseQuery(request));
        const formData = new FormData();
        for(let i = 0; i < files.length; i++) {
            const file = files[i];
            formData.append("file", file, file.name);
        }
        xhr.send(formData);
    });
}

/**
* function example_7.get_upload_data(
*     _type text,
*     _user_id text DEFAULT NULL::text
* )
* returns setof text[]
* 
* @remarks
* comment on function example_7.get_upload_data is 'HTTP GET
* @authorize';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: string[][], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_7.get_upload_data
*/
export async function getUploadData(
    request: IGetUploadDataRequest
) : Promise<{status: number, response: string[][], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-7/get-upload-data" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as string[][] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_7.login(
*     _username text,
*     _password text
* )
* returns table(
*     scheme text,
*     user_id integer,
*     username text
* )
* 
* @remarks
* comment on function example_7.login is 'HTTP POST
* @login
* @anonymous';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_7.login
*/
export async function login(
    request: ILoginRequest
) : Promise<{status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-7/login", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_7.logout()
* returns void
* 
* @remarks
* comment on function example_7.logout is 'HTTP POST
* @logout';
* 
* @returns {status: number, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_7.logout
*/
export async function logout() : Promise<{status: number, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-7/logout", {
        method: "POST",
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

