// autogenerated at 2026-04-02T13:02:09.8845460+02:00


const baseUrl = "";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

interface IAuthor {
    authorId: number | null;
    firstName: string | null;
    lastName: string | null;
}

interface IBooks {
    bookId: number | null;
    title: string | null;
    authorId: number | null;
}

interface IBooksInfo {
    books: number | null;
    activeReviews: number | null;
    avgRating: number | null;
}

interface ICreateAuthorRequest {
    author: string | null;
}

interface ICreateAuthorResponse {
    authorId: number | null;
    firstName: string | null;
    lastName: string | null;
}

interface IGetAuthorRequest {
    authorId: number | null;
}

interface IGetAuthorResponse {
    authorId: number | null;
    firstName: string | null;
    lastName: string | null;
}

interface IGetAuthorInfoRequest {
    authorId: number | null;
}

interface IGetAuthorInfoResponse {
    firstName: string | null;
    lastName: string | null;
    books: number | null;
}

interface IGetAuthorsRequest {
    authorId?: number | null;
}

interface IGetAuthorsResponse {
    authorId: number | null;
    firstName: string | null;
    lastName: string | null;
}

interface IGetAuthorsAndBooksRequest {
    authorId?: number | null;
}

interface IGetAuthorsAndBooksResponse {
    author: IAuthor | null;
    books: IBooks[] | null;
}

interface IGetAuthorsByFieldsRequest {
    author: string | null;
}

interface IGetAuthorsByFieldsResponse {
    authorId: number | null;
    firstName: string | null;
    lastName: string | null;
}

interface IGetAuthorsWithDetailsRequest {
    authorId?: number | null;
}

interface IGetAuthorsWithDetailsResponse {
    authorId: number | null;
    firstName: string | null;
    lastName: string | null;
    books: number | null;
}

interface IGetAuthorsWithDetailsNestedRequest {
    authorId?: number | null;
}

interface IGetAuthorsWithDetailsNestedResponse {
    author: IAuthor | null;
    books: number | null;
}

interface IGetAuthorsWithDetailsTypeRequest {
    authorId?: number | null;
}

interface IGetAuthorsWithDetailsTypeResponse {
    authorId: number | null;
    firstName: string | null;
    lastName: string | null;
    books: number | null;
    activeReviews: number | null;
    avgRating: number | null;
}

interface IGetAuthorsWithDetailsTypeNestedRequest {
    authorId?: number | null;
}

interface IGetAuthorsWithDetailsTypeNestedResponse {
    author: IAuthor | null;
    booksInfo: IBooksInfo | null;
}


/**
* SQL file: ../../npgsqlrest-docs/examples/12_custom_types_sql_file/sql/create-author.sql
* 
* @remarks
* HTTP POST
* param $1 author example_12.authors
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<ICreateAuthorResponse[]>}
*/
export async function createAuthor(
    request: ICreateAuthorRequest
) : Promise<ApiResult<ICreateAuthorResponse[]>> {
    const response = await fetch(baseUrl + "/api/create-author", {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as ICreateAuthorResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/12_custom_types_sql_file/sql/get-author.sql
* 
* @remarks
* HTTP GET
* param $1 authorId int
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IGetAuthorResponse[]>}
*/
export async function getAuthor(
    request: IGetAuthorRequest
) : Promise<ApiResult<IGetAuthorResponse[]>> {
    const response = await fetch(baseUrl + "/api/get-author" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/12_custom_types_sql_file/sql/get-author-info.sql
* 
* @remarks
* HTTP GET
* param $1 authorId int
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IGetAuthorInfoResponse[]>}
*/
export async function getAuthorInfo(
    request: IGetAuthorInfoRequest
) : Promise<ApiResult<IGetAuthorInfoResponse[]>> {
    const response = await fetch(baseUrl + "/api/get-author-info" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorInfoResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/12_custom_types_sql_file/sql/get-authors.sql
* 
* @remarks
* HTTP GET
* param $1 authorId int default null
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IGetAuthorsResponse[]>}
*/
export async function getAuthors(
    request: IGetAuthorsRequest
) : Promise<ApiResult<IGetAuthorsResponse[]>> {
    const response = await fetch(baseUrl + "/api/get-authors" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/12_custom_types_sql_file/sql/get-authors-and-books.sql
* 
* @remarks
* HTTP GET
* nested
* param $1 authorId int default null
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IGetAuthorsAndBooksResponse[]>}
*/
export async function getAuthorsAndBooks(
    request: IGetAuthorsAndBooksRequest
) : Promise<ApiResult<IGetAuthorsAndBooksResponse[]>> {
    const response = await fetch(baseUrl + "/api/get-authors-and-books" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorsAndBooksResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/12_custom_types_sql_file/sql/get-authors-by-fields.sql
* 
* @remarks
* HTTP GET
* param $1 author example_12.authors
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IGetAuthorsByFieldsResponse[]>}
*/
export async function getAuthorsByFields(
    request: IGetAuthorsByFieldsRequest
) : Promise<ApiResult<IGetAuthorsByFieldsResponse[]>> {
    const response = await fetch(baseUrl + "/api/get-authors-by-fields" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorsByFieldsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/12_custom_types_sql_file/sql/get-authors-with-details.sql
* 
* @remarks
* HTTP GET
* param $1 authorId int default null
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IGetAuthorsWithDetailsResponse[]>}
*/
export async function getAuthorsWithDetails(
    request: IGetAuthorsWithDetailsRequest
) : Promise<ApiResult<IGetAuthorsWithDetailsResponse[]>> {
    const response = await fetch(baseUrl + "/api/get-authors-with-details" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorsWithDetailsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/12_custom_types_sql_file/sql/get-authors-with-details-nested.sql
* 
* @remarks
* HTTP GET
* nested
* param $1 authorId int default null
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IGetAuthorsWithDetailsNestedResponse[]>}
*/
export async function getAuthorsWithDetailsNested(
    request: IGetAuthorsWithDetailsNestedRequest
) : Promise<ApiResult<IGetAuthorsWithDetailsNestedResponse[]>> {
    const response = await fetch(baseUrl + "/api/get-authors-with-details-nested" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorsWithDetailsNestedResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/12_custom_types_sql_file/sql/get-authors-with-details-type.sql
* 
* @remarks
* HTTP GET
* param $1 authorId int default null
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IGetAuthorsWithDetailsTypeResponse[]>}
*/
export async function getAuthorsWithDetailsType(
    request: IGetAuthorsWithDetailsTypeRequest
) : Promise<ApiResult<IGetAuthorsWithDetailsTypeResponse[]>> {
    const response = await fetch(baseUrl + "/api/get-authors-with-details-type" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorsWithDetailsTypeResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/12_custom_types_sql_file/sql/get-authors-with-details-type-nested.sql
* 
* @remarks
* HTTP GET
* nested
* param $1 authorId int default null
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IGetAuthorsWithDetailsTypeNestedResponse[]>}
*/
export async function getAuthorsWithDetailsTypeNested(
    request: IGetAuthorsWithDetailsTypeNestedRequest
) : Promise<ApiResult<IGetAuthorsWithDetailsTypeNestedResponse[]>> {
    const response = await fetch(baseUrl + "/api/get-authors-with-details-type-nested" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorsWithDetailsTypeNestedResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

