@host=http://127.0.0.1:8080

// function example_11.login(
//     _username text,
//     _password text
// )
// returns table(
//     scheme text,
//     user_id integer,
//     user_name text
// )
//
// comment on function example_11.login is 'HTTP POST
// login
// anonymous';
POST {{host}}/api/example-11/login
content-type: application/json

{
    "username": "ABC",
    "password": "XYZ"
}

###

// function example_11.logout()
// returns void
//
// comment on function example_11.logout is 'HTTP POST
// logout';
POST {{host}}/api/example-11/logout

###

// select example_11.contacts
//
// comment on function example_11.contacts is 'HTTP
// disabled
// enabled select, insert_returning, update, delete';
GET {{host}}/api/example-11/contacts?id=1&name=XYZ&email=IJK&phone=ABC&createdAt=2024-05-05T04%3A04%3A04.00

###

// update example_11.contacts
//
// comment on function example_11.contacts is 'HTTP
// disabled
// enabled select, insert_returning, update, delete';
POST {{host}}/api/example-11/contacts
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "email": "IJK",
    "phone": "ABC",
    "createdAt": "2024-05-05T04:04:04.00"
}

###

// update example_11.contacts
// returning
//     id, name, email, phone, created_at
//
// comment on function example_11.contacts is 'HTTP
// disabled
// enabled select, insert_returning, update, delete';
POST {{host}}/api/example-11/contacts/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "email": "IJK",
    "phone": "ABC",
    "createdAt": "2024-05-05T04:04:04.00"
}

###

// delete from example_11.contacts
//
// comment on function example_11.contacts is 'HTTP
// disabled
// enabled select, insert_returning, update, delete';
DELETE {{host}}/api/example-11/contacts?id=1&name=XYZ&email=IJK&phone=ABC&createdAt=2024-05-05T04%3A04%3A04.00

###

// delete from example_11.contacts
// returning
//     id, name, email, phone, created_at
//
// comment on function example_11.contacts is 'HTTP
// disabled
// enabled select, insert_returning, update, delete';
DELETE {{host}}/api/example-11/contacts/returning?id=1&name=XYZ&email=IJK&phone=ABC&createdAt=2024-05-05T04%3A04%3A04.00

###

// insert into example_11.contacts
// returning
//     id, name, email, phone, created_at
//
// comment on function example_11.contacts is 'HTTP
// disabled
// enabled select, insert_returning, update, delete';
PUT {{host}}/api/example-11/contacts/returning
content-type: application/json

{
    "id": 1,
    "name": "XYZ",
    "email": "IJK",
    "phone": "ABC",
    "createdAt": "2024-05-05T04:04:04.00"
}

###

