// autogenerated at 2026-07-08T13:45:19.1544920+02:00


import {
    useQuery,
    useMutation,
    type UseQueryOptions,
    type UseMutationOptions,
} from "@tanstack/react-query";
import * as api from "./example23Api";

type CreateTodoRequest = Parameters<typeof api.createTodo>[0];
type CreateTodoResult = Awaited<ReturnType<typeof api.createTodo>>;

export function useCreateTodoMutation(
    options?: Omit<
        UseMutationOptions<CreateTodoResult, unknown, CreateTodoRequest>,
        "mutationFn"
    >,
) {
    return useMutation({
        mutationFn: (request: CreateTodoRequest) => api.createTodo(request),
        ...options,
    });
}

type GetStatsResult = Awaited<ReturnType<typeof api.getStats>>;

export const getStatsKeys = {
    all: ["example23", "getStats"] as const,
};

export function useGetStats(
    options?: Omit<
        UseQueryOptions<GetStatsResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: getStatsKeys.all,
        queryFn: () => api.getStats(),
        ...options,
    });
}

type SearchTodosRequest = Parameters<typeof api.searchTodos>[0];
type SearchTodosResult = Awaited<ReturnType<typeof api.searchTodos>>;

export const searchTodosKeys = {
    all: ["example23", "searchTodos"] as const,
    byRequest: (request: SearchTodosRequest) =>
        ["example23", "searchTodos", request] as const,
};

export function useSearchTodos(
    request: SearchTodosRequest,
    options?: Omit<
        UseQueryOptions<SearchTodosResult>,
        "queryKey" | "queryFn"
    >,
) {
    return useQuery({
        queryKey: searchTodosKeys.byRequest(request),
        queryFn: () => api.searchTodos(request),
        ...options,
    });
}
