// autogenerated at 2026-07-08T13:45:19.1528740+02:00


const baseUrl = "";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

interface ICreateTodoRequest {
    title: string | null;
}

interface IGetStatsResponse {
    total: number | null;
    done: number | null;
}

interface ISearchTodosRequest {
    search: string | null;
    done?: boolean | null;
}

interface ISearchTodosResponse {
    id: number | null;
    title: string | null;
    done: boolean | null;
}


/**
* function example_23.create_todo(
*     _title text
* )
* returns integer
* 
* @remarks
* comment on function example_23.create_todo is 'HTTP POST
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<number>}
* 
* @see FUNCTION example_23.create_todo
*/
export async function createTodo(
    request: ICreateTodoRequest
) : Promise<ApiResult<number>> {
    const response = await fetch(baseUrl + "/api/example-23/create-todo", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? Number(await response.text()) : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function example_23.get_stats()
* returns table(
*     total integer,
*     done integer
* )
* 
* @remarks
* comment on function example_23.get_stats is 'HTTP GET
* single';
* 
* @returns {ApiResult<IGetStatsResponse>}
* 
* @see FUNCTION example_23.get_stats
*/
export async function getStats() : Promise<ApiResult<IGetStatsResponse>> {
    const response = await fetch(baseUrl + "/api/example-23/get-stats", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetStatsResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function example_23.internal_recalculate()
* returns void
* 
* @remarks
* comment on function example_23.internal_recalculate is 'HTTP POST
* tsclient_hooks=off';
* 
* @returns {status: number, error: ApiError | undefined}
* 
* @see FUNCTION example_23.internal_recalculate
*/
export async function internalRecalculate() : Promise<{status: number, error: ApiError | undefined}> {
    const response = await fetch(baseUrl + "/api/example-23/internal-recalculate", {
        method: "POST",
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function example_23.search_todos(
*     _search text,
*     _done boolean DEFAULT NULL::boolean
* )
* returns table(
*     id integer,
*     title text,
*     done boolean
* )
* 
* @remarks
* comment on function example_23.search_todos is 'HTTP GET
* request_param_type query_string';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<ISearchTodosResponse[]>}
* 
* @see FUNCTION example_23.search_todos
*/
export async function searchTodos(
    request: ISearchTodosRequest
) : Promise<ApiResult<ISearchTodosResponse[]>> {
    const response = await fetch(baseUrl + "/api/example-23/search-todos" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as ISearchTodosResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

