@host=http://127.0.0.1:8080

// SQL file: ../../npgsqlrest-docs/examples/9_http_calls_sql_file/sql/login.sql
//
// HTTP POST
// @login
// @allow_anonymous
// @param $1 username
// @param $2 password
POST {{host}}/api/login
content-type: application/json

{
    "username": "ABC",
    "password": "XYZ"
}

###

// SQL file: ../../npgsqlrest-docs/examples/9_http_calls_sql_file/sql/financial-dashboard.sql
//
// HTTP GET /financial-dashboard
// @authorize
// @param $1 _base_currency text
// @param $2 _target_currencies_csv text
// @param $3 _crypto_ids_csv text
// @param $4 _vs_currencies_csv text
// @param $5 _exchange_rate_response example_9.exchange_rate_api
// @param $6 _crypto_response example_9.crypto_price_api
//  @skip
//  @result dashboard
//  @single
//  @returns example_9.financial_dashboard_result
GET {{host}}/financial-dashboard?_base_currency=ABC&_target_currencies_csv=XYZ&_crypto_ids_csv=IJK&_vs_currencies_csv=ABC&_exchange_rate_response=XYZ&_crypto_response=IJK

###

// SQL file: ../../npgsqlrest-docs/examples/9_http_calls_sql_file/sql/logout.sql
//
//  HTTP POST
//  @logout
//  @authorize
POST {{host}}/api/logout

###

