// autogenerated at 2026-07-03T19:35:00.3607610+02:00


const baseUrl = "";

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

interface IGetPostsResponse {
    username: string | null;
    content: string | null;
    createdAt: string | null;
}

interface IGetUsersResponse {
    userId: number | null;
    username: string | null;
    email: string | null;
    active: boolean | null;
}


/**
* function example_2.get_posts()
* returns table(
*     username text,
*     content text,
*     created_at timestamp without time zone
* )
* 
* @remarks
* comment on function example_2.get_posts is 'HTTP GET
* 
* @returns {ApiResult<IGetPostsResponse[]>}
* 
* @see FUNCTION example_2.get_posts
*/
export async function getPosts() : Promise<ApiResult<IGetPostsResponse[]>> {
    const response = await fetch(baseUrl + "/api/example-2/get-posts", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetPostsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* function example_2.get_users()
* returns table(
*     user_id integer,
*     username text,
*     email text,
*     active boolean
* )
* 
* @remarks
* comment on function example_2.get_users is 'HTTP GET
* 
* @returns {ApiResult<IGetUsersResponse[]>}
* 
* @see FUNCTION example_2.get_users
*/
export async function getUsers() : Promise<ApiResult<IGetUsersResponse[]>> {
    const response = await fetch(baseUrl + "/api/example-2/get-users", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetUsersResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

