// autogenerated at 2026-03-28T12:06:01.6571470+01:00


const baseUrl = "";

interface IGetPostsResponse {
    username: string | null;
    content: string | null;
    createdAt: string | null;
}

interface IGetUsersResponse {
    userId: number | null;
    username: string | null;
    email: string | null;
    active: boolean | null;
}


/**
* function example_2.get_posts()
* returns table(
*     username text,
*     content text,
*     created_at timestamp without time zone
* )
* 
* @remarks
* comment on function example_2.get_posts is 'HTTP GET
* 
* @returns {status: number, response: IGetPostsResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_2.get_posts
*/
export async function getPosts() : Promise<{status: number, response: IGetPostsResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-2/get-posts", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetPostsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_2.get_users()
* returns table(
*     user_id integer,
*     username text,
*     email text,
*     active boolean
* )
* 
* @remarks
* comment on function example_2.get_users is 'HTTP GET
* 
* @returns {status: number, response: IGetUsersResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_2.get_users
*/
export async function getUsers() : Promise<{status: number, response: IGetUsersResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-2/get-users", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetUsersResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

