-- Example 20: test runner with fixtures (deferrable constraints) on a fresh-per-run schema.
--
-- Repeatable migration (R__): drops and recreates everything, so it is safe to re-run and is re-applied
-- by the test Setup on every `--test` run (see ../config.json → TestRunner.Setup). The ENDPOINTS are the
-- .sql files in ./sql (served by SqlFileSource); their tests are the co-located *.test.sql files.

drop schema if exists example_20 cascade;
create schema example_20;
create extension if not exists pgcrypto;   -- crypt()/gen_salt() for password hashing

-- Reference tables.
create table example_20.countries (
    id   int  generated by default as identity primary key,
    code text not null unique,
    name text not null
);

create table example_20.roles (
    id   int  generated by default as identity primary key,
    name text not null unique
);

-- A user has exactly one role; an address belongs to a user and a country.
-- Every foreign key is DEFERRABLE INITIALLY IMMEDIATE: normal writes are still checked immediately, but a
-- test can `set constraints all deferred` and then insert ONLY the rows it needs (in any order). The
-- deferred checks would fire at COMMIT — which a rolled-back test never reaches — so partial fixtures are
-- fine.
create table example_20.users (
    id            int  generated by default as identity primary key,
    email         text not null unique,
    full_name     text not null,
    password_hash text not null,
    role_id       int  not null references example_20.roles(id)     deferrable initially immediate
);

create table example_20.addresses (
    id         int  generated by default as identity primary key,
    user_id    int  not null references example_20.users(id)        deferrable initially immediate,
    country_id int  not null references example_20.countries(id)    deferrable initially immediate,
    line1      text not null,
    city       text not null
);

-- Baseline seed: the running app and the "list users" endpoint see these three users.
insert into example_20.countries (id, code, name) values
    (1, 'US', 'United States'),
    (2, 'GB', 'United Kingdom');

insert into example_20.roles (id, name) values
    (1, 'admin'),
    (2, 'user');

insert into example_20.users (id, email, full_name, password_hash, role_id) values
    (1, 'ada@example.com',   'Ada Lovelace', crypt('ada-secret',   gen_salt('bf')), 1),
    (2, 'alan@example.com',  'Alan Turing',  crypt('alan-secret',  gen_salt('bf')), 2),
    (3, 'grace@example.com', 'Grace Hopper', crypt('grace-secret', gen_salt('bf')), 2);

insert into example_20.addresses (id, user_id, country_id, line1, city) values
    (1, 1, 2, '1 Analytical Way', 'London'),
    (2, 2, 2, '2 Turing Avenue',  'Manchester');
