// autogenerated at 2026-01-03T11:45:55.3784490+01:00


const baseUrl = "http://127.0.0.1:8080";


/**
* function example_1.my_first_function()
* returns setof text
* 
* @remarks
* comment on function example_1.my_first_function is 'HTTP GET
* 
* @returns {status: number, response: string[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_1.my_first_function
*/
export async function myFirstFunction() : Promise<{status: number, response: string[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-1/my-first-function", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as string[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

