@host=https://localhost:8080;http://localhost:8081

// function example_5_public.sales_report(
//     _user_name text DEFAULT NULL::text
// )
// returns table(
//     exported_by text,
//     order_id integer,
//     customer_name text,
//     product text,
//     quantity integer,
//     unit_price numeric(10,2),
//     total numeric(10,2),
//     order_date date
// )
//
// comment on function example_5_public.sales_report is 'HTTP GET
// @raw
// @separator ,
// @new_line \n
// @columns
// Content-Type: text/csv
// Content-Disposition: attachment; filename="sales_report.csv"
// @basic_auth admin lgjSqahngJF9DN0W+2vAf+EDgxSs14e9ag+DezupGdsftJJ8DUphu6cfroMB6Uqp
// @user_params';
GET {{host}}/api/example-5-public/sales-report?userName=ABC

###

