// autogenerated at 2026-02-01T12:06:56.8300080+01:00


const baseUrl = "http://localhost:8080";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

interface IIsPasskeyEnabledRequest {
    userId?: string | null;
}

interface IListPasskeyUsersResponse {
    userId: number | null;
    username: string | null;
    pass: string | null;
    email: string | null;
    passkeyEnabled: boolean | null;
}

interface ILoginRequest {
    username: string | null;
    password: string | null;
}

interface IWhoAmIRequest {
    userId?: string | null;
    username?: string | null;
    email?: string | null;
}

interface IWhoAmIResponse {
    userId: string | null;
    username: string | null;
    email: string | null;
}


/**
* function example_13.is_passkey_enabled(
*     _user_id text DEFAULT NULL::text
* )
* returns boolean
* 
* @remarks
* comment on function example_13.is_passkey_enabled is 'HTTP GET
* @authorize';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: boolean, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_13.is_passkey_enabled
*/
export async function isPasskeyEnabled(
    request: IIsPasskeyEnabledRequest
) : Promise<{status: number, response: boolean, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-13/is-passkey-enabled" + parseQuery(request), {
        method: "GET",
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() == "t" : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_13.list_passkey_users()
* returns table(
*     user_id integer,
*     username text,
*     pass text,
*     email text,
*     passkey_enabled boolean
* )
* 
* @remarks
* comment on function example_13.list_passkey_users is 'HTTP GET
* @anonymous';
* 
* @returns {status: number, response: IListPasskeyUsersResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_13.list_passkey_users
*/
export async function listPasskeyUsers() : Promise<{status: number, response: IListPasskeyUsersResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-13/list-passkey-users", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IListPasskeyUsersResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_13.login(
*     _username text,
*     _password text
* )
* returns table(
*     scheme text,
*     user_id integer,
*     username text,
*     email text,
*     message jsonb
* )
* 
* @remarks
* comment on function example_13.login is 'HTTP POST
* @login
* @anonymous';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_13.login
*/
export async function login(
    request: ILoginRequest
) : Promise<{status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-13/login", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_13.logout()
* returns void
* 
* @remarks
* comment on function example_13.logout is 'HTTP POST
* @logout';
* 
* @returns {status: number, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_13.logout
*/
export async function logout() : Promise<{status: number, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-13/logout", {
        method: "POST",
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_13.who_am_i(
*     _user_id text DEFAULT NULL::text,
*     _username text DEFAULT NULL::text,
*     _email text DEFAULT NULL::text
* )
* returns table(
*     user_id text,
*     username text,
*     email text
* )
* 
* @remarks
* comment on function example_13.who_am_i is 'HTTP GET
* @authorize';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IWhoAmIResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_13.who_am_i
*/
export async function whoAmI(
    request: IWhoAmIRequest
) : Promise<{status: number, response: IWhoAmIResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-13/who-am-i" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IWhoAmIResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

