// autogenerated at 2026-03-29T09:41:57.6374790+02:00
const baseUrl = "";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

interface ILoginRequest {
    username: string | null;
    password: string | null;
}

interface IWhoAmIRequest {
    _user_id?: string | null;
    _username?: string | null;
    _email?: string | null;
}

interface IWhoAmIResponse {
    userId: string | null;
    username: string | null;
    email: string | null;
}


/**
* SQL file: ../../npgsqlrest-docs/examples/3_security_and_auth_sql_file/sql_3/login.sql
* 
* @remarks
* HTTP POST
* @login
* @allow_anonymous
* @param $1 username
* @param $2 password
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see SQLFILE public.login
*/
export async function login(
    request: ILoginRequest
) : Promise<{status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/login", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/3_security_and_auth_sql_file/sql_3/logout.sql
* 
* @remarks
*  HTTP POST
*  @logout
*  @authorize
* 
* @returns {status: number, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see SQLFILE public.logout
*/
export async function logout() : Promise<{status: number, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/logout", {
        method: "POST",
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/3_security_and_auth_sql_file/sql_3/who-am-i.sql
* 
* @remarks
* HTTP GET
* @authorize
* @user_parameters
* @param $1 _user_id default null
* @param $2 _username default null
* @param $3 _email default null
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IWhoAmIResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see SQLFILE public.who-am-i
*/
export async function whoAmI(
    request: IWhoAmIRequest
) : Promise<{status: number, response: IWhoAmIResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/who-am-i" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IWhoAmIResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

