// autogenerated at 2026-06-13T12:29:54.6900940+02:00


const baseUrl = "";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

export interface ICancelOrderRequest {
    orderId: number | null;
}

export interface IGetProductRequest {
    id: number | null;
}

export interface IGetProductResponse {
    id: number | null;
    name: string | null;
    category: string | null;
    price: number | null;
    stock: number | null;
}

export interface ILoginRequest {
    username: string | null;
    password?: string | null;
}

export interface IPlaceOrderRequest {
    productId: number | null;
    quantity?: number | null;
}

export interface IPlaceOrderResponse {
    orderId: number | null;
    product: string | null;
    quantity: number | null;
    total: number | null;
    status: string | null;
}

export interface IRestockProductRequest {
    productId: number | null;
    newStock: number | null;
}

export interface IRestockProductResponse {
    id: number | null;
    name: string | null;
    category: string | null;
    stock: number | null;
}

export interface ISearchProductsRequest {
    query?: string | null;
    maxPrice?: number | null;
}

export interface ISearchProductsResponse {
    id: number | null;
    name: string | null;
    category: string | null;
    price: number | null;
    stock: number | null;
}


/**
* SQL file: ./15_mcp_server/sql/cancel_order.sql
* 
* @remarks
* HTTP DELETE
* param $1 orderId int
* mcp Cancel an order by id and return its quantity to stock.
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<string[]>}
*/
export async function cancelOrder(
    request: ICancelOrderRequest
) : Promise<ApiResult<string[]>> {
    const response = await fetch(baseUrl + "/api/cancel-order", {
        method: "DELETE",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as string[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ./15_mcp_server/sql/get_product.sql
* 
* @remarks
* HTTP GET
* param $1 id int
* single
* mcp_description Get a single product by its id, including price and current stock.
*  Dev note: @mcp_description above is the authoritative tool description and opts the routine in (like
*  mcp), so this comment is IGNORED — an explicit description suppresses comment prose, so notes like this
*  never leak into what the agent sees. (Without an explicit description, prose would become the description.)
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IGetProductResponse>}
*/
export async function getProduct(
    request: IGetProductRequest
) : Promise<ApiResult<IGetProductResponse>> {
    const response = await fetch(baseUrl + "/api/get-product" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetProductResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ./15_mcp_server/sql/list_categories.sql
* 
* @remarks
* HTTP GET
* mcp List all distinct product categories in the catalog.
* 
* @returns {ApiResult<string[]>}
*/
export async function listCategories() : Promise<ApiResult<string[]>> {
    const response = await fetch(baseUrl + "/api/list-categories", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as string[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ./15_mcp_server/sql/login.sql
* 
* @remarks
* HTTP POST
* login
* allow_anonymous
* param $1 username
* define_param password text
*  Issues a JWT for a staff member. `scheme = 'jwt'` selects the JWT auth scheme (see config.json Auth),
*  so a successful response body carries { accessToken, refreshToken, tokenType, expiresIn, ... }.
*  `password` is declared with @define_param: it is accepted from the request but NOT bound to the SQL —
*  NpgsqlRest's built-in verifier matches it against the returned password_hash column (HashColumnName).
*  The `roles` column becomes the token's role claims, which is what `@authorize manager` checks later.
*  This is a REST-only endpoint (no @mcp): you log in over HTTP, then present the token to the MCP tools.
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<string>}
*/
export async function login(
    request: ILoginRequest
) : Promise<ApiResult<string>> {
    const response = await fetch(baseUrl + "/api/login", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ./15_mcp_server/sql/place_order.sql
* 
* @remarks
* HTTP POST
* param $1 productId int
* param $2 quantity int default 1
* single
* mcp Place an order for a product. Decrements stock and returns the created order.
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IPlaceOrderResponse>}
*/
export async function placeOrder(
    request: IPlaceOrderRequest
) : Promise<ApiResult<IPlaceOrderResponse>> {
    const response = await fetch(baseUrl + "/api/place-order", {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IPlaceOrderResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ./15_mcp_server/sql/product_count.sql
* 
* @remarks
* HTTP GET
* single
* mcp Total number of products in the catalog.
* mcp_name catalog_size
* 
* @returns {ApiResult<number>}
*/
export async function productCount() : Promise<ApiResult<number>> {
    const response = await fetch(baseUrl + "/api/product-count", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as number : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ./15_mcp_server/sql/restock_product.sql
* 
* @remarks
* HTTP POST
* param $1 productId int
* param $2 newStock int
* single
* authorize manager
* mcp Set a product's stock to an exact value. Manager-only — a privileged, mutating operation.
*  The ONLY protected operation in this example. `@authorize manager` gates it by role, so the same
*  routine enforces auth on BOTH interfaces it is exposed on:
*    • REST   POST /api/restock-product   (Authorization: Bearer <jwt>)
*    • MCP    tools/call restock_product  (Authorization: Bearer <jwt> on the /mcp request)
*  Outcomes the demo shows: no token → 401; a 'staff'-role token (clerk) → 403; a 'manager' token → success.
*  Everything else in the store stays anonymous — enabling JWT auth does not require gating the endpoint.
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IRestockProductResponse>}
*/
export async function restockProduct(
    request: IRestockProductRequest
) : Promise<ApiResult<IRestockProductResponse>> {
    const response = await fetch(baseUrl + "/api/restock-product", {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IRestockProductResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ./15_mcp_server/sql/search_products.sql
* 
* @remarks
* HTTP GET
* param $1 query text default null
* param $2 maxPrice numeric default null
* mcp Search the product catalog by name or category and/or a maximum price; returns matching products with their price and stock.
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<ISearchProductsResponse[]>}
*/
export async function searchProducts(
    request: ISearchProductsRequest
) : Promise<ApiResult<ISearchProductsResponse[]>> {
    const response = await fetch(baseUrl + "/api/search-products" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as ISearchProductsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

