// autogenerated at 2026-01-06T10:35:34.0277570+01:00


const baseUrl = "http://127.0.0.1:8080";
export const createSendMessageEventSource = (id: string = "") => new EventSource(baseUrl + "/api/example-8/send-message/info?" + id);

interface IGetMessagesResponse {
    messageId: number | null;
    userId: number | null;
    username: string | null;
    messageText: string | null;
    createdAt: string | null;
}

interface ILoginRequest {
    username: string | null;
    password: string | null;
}

interface ISendMessageRequest {
    messageText: string | null;
    userId?: string | null;
    userName?: string | null;
}


/**
* function example_8.get_messages()
* returns table(
*     message_id integer,
*     user_id integer,
*     username text,
*     message_text text,
*     created_at timestamp with time zone
* )
* 
* @remarks
* comment on function example_8.get_messages is 'HTTP GET
* authorize';
* 
* @returns {status: number, response: IGetMessagesResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_8.get_messages
*/
export async function getMessages() : Promise<{status: number, response: IGetMessagesResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-8/get-messages", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetMessagesResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_8.login(
*     _username text,
*     _password text
* )
* returns table(
*     scheme text,
*     user_id integer,
*     user_name text
* )
* 
* @remarks
* comment on function example_8.login is 'HTTP POST
* login
* anonymous';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_8.login
*/
export async function login(
    request: ILoginRequest
) : Promise<{status: number, response: string, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-8/login", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_8.logout()
* returns void
* 
* @remarks
* comment on function example_8.logout is 'HTTP POST
* logout';
* 
* @returns {status: number, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_8.logout
*/
export async function logout() : Promise<{status: number, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-8/logout", {
        method: "POST",
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* procedure example_8.send_message(
*     _message_text text,
*     _user_id text DEFAULT NULL::text,
*     _user_name text DEFAULT NULL::text
* )
* returns void
* 
* @remarks
* comment on function example_8.send_message is 'HTTP POST
* authorize
* sse
* sse_scope authorize';
* 
* @param request - Object containing request parameters.
* @param onMessage - Optional callback function to handle incoming SSE messages.
* @param id - Optional execution ID for SSE connection. When supplied, only EventSource object with this ID in query string will will receive events.
* @param closeAfterMs - Time in milliseconds to wait before closing the EventSource connection. Used only when onMessage callback is provided.
* @param awaitConnectionMs - Time in milliseconds to wait after opening the EventSource connection before sending the request. Used only when onMessage callback is provided.
* @returns {status: number, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see PROCEDURE example_8.send_message
*/
export async function sendMessage(
    request: ISendMessageRequest,
    onMessage?: (message: string) => void,
    id: string | undefined = undefined,
    closeAfterMs = 1000,
    awaitConnectionMs: number | undefined = 0
) : Promise<{status: number, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const executionId = id ? id : window.crypto.randomUUID();
    let eventSource: EventSource;
    if (onMessage) {
        eventSource = createSendMessageEventSource(executionId);
        eventSource.onmessage = (event: MessageEvent) => {
            onMessage(event.data);
        };
        if (awaitConnectionMs !== undefined) {
            await new Promise(resolve => setTimeout(resolve, awaitConnectionMs));
        }
    }
    try {
        const response = await fetch(baseUrl + "/api/example-8/send-message", {
            method: "POST",
            headers: {
                "X-NpgsqlRest-ID": executionId
            },
            body: JSON.stringify(request)
        });
        return {
            status: response.status,
            error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
        };
    }
    finally {
        if (onMessage) {
            setTimeout(() => eventSource.close(), closeAfterMs);
        }
    }
}

