// autogenerated at 2026-04-01T12:51:21.0551970+02:00


const baseUrl = "";
export const createSendMessageEventSource = (id: string = "") => new EventSource(baseUrl + "/api/send-message/info?" + id);

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

interface IGetMessagesResponse {
    messageId: number | null;
    userId: number | null;
    username: string | null;
    messageText: string | null;
    createdAt: string | null;
}

interface ILoginRequest {
    username: string | null;
    password: string | null;
}

interface ISendMessageRequest {
    messageText: string | null;
    _user_id?: string | null;
    _user_name?: string | null;
}

interface ISendMessageResponse {
    result1: string[];
    result2: string[];
    result3: string[];
}


/**
* SQL file: ./8_simple_chat_client_sql_file/sql/get-messages.sql
* 
* @remarks
*  HTTP GET
*  @authorize
* 
* @returns {ApiResult<IGetMessagesResponse[]>}
*/
export async function getMessages() : Promise<ApiResult<IGetMessagesResponse[]>> {
    const response = await fetch(baseUrl + "/api/get-messages", {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetMessagesResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ./8_simple_chat_client_sql_file/sql/login.sql
* 
* @remarks
* HTTP POST
* @login
* @anonymous
* @param $1 username
* @param $2 password
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<string>}
*/
export async function login(
    request: ILoginRequest
) : Promise<ApiResult<string>> {
    const response = await fetch(baseUrl + "/api/login", {
        method: "POST",
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ./8_simple_chat_client_sql_file/sql/logout.sql
* 
* @remarks
*  HTTP POST
*  @logout
*  @authorize
* 
* @returns {status: number, error: ApiError | undefined}
*/
export async function logout() : Promise<{status: number, error: ApiError | undefined}> {
    const response = await fetch(baseUrl + "/api/logout", {
        method: "POST",
    });
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ./8_simple_chat_client_sql_file/sql/send-message.sql
* 
* @remarks
* HTTP POST
* @authorize
* @sse
* @sse_scope authorize
* @user_parameters
* @param $1 messageText text
* @param $2 _user_id text = null
* @param $3 _user_name text = null
* @void
* 
* @param request - Object containing request parameters.
* @param onMessage - Optional callback function to handle incoming SSE messages.
* @param id - Optional execution ID for SSE connection. When supplied, only EventSource object with this ID in query string will will receive events.
* @param closeAfterMs - Time in milliseconds to wait before closing the EventSource connection. Used only when onMessage callback is provided.
* @param awaitConnectionMs - Time in milliseconds to wait after opening the EventSource connection before sending the request. Used only when onMessage callback is provided.
* @returns {ApiResult<ISendMessageResponse>}
*/
export async function sendMessage(
    request: ISendMessageRequest,
    onMessage?: (message: string) => void,
    id: string | undefined = undefined,
    closeAfterMs = 1000,
    awaitConnectionMs: number | undefined = 0
) : Promise<ApiResult<ISendMessageResponse>> {
    const executionId = id ? id : window.crypto.randomUUID();
    let eventSource: EventSource;
    if (onMessage) {
        eventSource = createSendMessageEventSource(executionId);
        eventSource.onmessage = (event: MessageEvent) => {
            onMessage(event.data);
        };
        if (awaitConnectionMs !== undefined) {
            await new Promise(resolve => setTimeout(resolve, awaitConnectionMs));
        }
    }
    try {
        const response = await fetch(baseUrl + "/api/send-message", {
            method: "POST",
            headers: {
                "X-NpgsqlRest-ID": executionId
            },
            body: JSON.stringify(request)
        });
        return {
            status: response.status,
            response: response.ok ? await response.json() as ISendMessageResponse : undefined!,
            error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
        };
    }
    finally {
        if (onMessage) {
            setTimeout(() => eventSource.close(), closeAfterMs);
        }
    }
}

