// autogenerated at 2026-01-19T08:25:42.2006090+01:00


const baseUrl = "http://127.0.0.1:8080";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

interface IAuthor {
    authorId: number | null;
    firstName: string | null;
    lastName: string | null;
}

interface IBooks {
    bookId: number | null;
    title: string | null;
    authorId: number | null;
}

interface IReviews {
    reviewId: number | null;
    bookId: number | null;
    reviewerName: string | null;
    rating: number | null;
    reviewText: string | null;
    createdAt: string | null;
}

interface IBooks1 {
    bookId: number | null;
    title: string | null;
    reviews: IReviews[] | null;
}

interface IBooksInfo {
    books: number | null;
    activeReviews: number | null;
    avgRating: number | null;
}

interface ICreateAuthorRequest {
    authorAuthorId?: number | null;
    authorFirstName?: string | null;
    authorLastName?: string | null;
}

interface ICreateAuthorResponse {
    authorId: number | null;
    firstName: string | null;
    lastName: string | null;
}

interface IGetAuthorRequest {
    authorId: number | null;
}

interface IGetAuthorResponse {
    authorId: number | null;
    firstName: string | null;
    lastName: string | null;
}

interface IGetAuthorInfoRequest {
    authorId: number | null;
}

interface IGetAuthorInfoResponse {
    firstName: string | null;
    lastName: string | null;
    books: number | null;
}

interface IGetAuthorsRequest {
    authorAuthorId?: number | null;
    authorFirstName?: string | null;
    authorLastName?: string | null;
}

interface IGetAuthorsResponse {
    authorId: number | null;
    firstName: string | null;
    lastName: string | null;
}

interface IGetAuthorsAndBooksRequest {
    authorId: number | null;
}

interface IGetAuthorsAndBooksResponse {
    author: IAuthor | null;
    books: IBooks[] | null;
}

interface IGetAuthorsAndBooksAndReviewsRequest {
    authorId: number | null;
}

interface IGetAuthorsAndBooksAndReviewsResponse {
    author: IAuthor | null;
    books: IBooks1[] | null;
}

interface IGetAuthorsWithDetailsRequest {
    authorId: number | null;
}

interface IGetAuthorsWithDetailsResponse {
    author: IAuthor | null;
    books: number | null;
}

interface IGetAuthorsWithDetailsNestedRequest {
    authorId: number | null;
}

interface IGetAuthorsWithDetailsNestedResponse {
    author: IAuthor | null;
    books: number | null;
}

interface IGetAuthorsWithDetailsTypeRequest {
    authorId: number | null;
}

interface IGetAuthorsWithDetailsTypeResponse {
    author: IAuthor | null;
    booksInfo: IBooksInfo | null;
}

interface IGetAuthorsWithDetailsTypeNestedRequest {
    authorId: number | null;
}

interface IGetAuthorsWithDetailsTypeNestedResponse {
    author: IAuthor | null;
    booksInfo: IBooksInfo | null;
}


/**
* function example_12.create_author(
*     _author_author_id integer,
*     _author_first_name text,
*     _author_last_name text
* )
* returns record
* 
* @remarks
* comment on function example_12.create_author is 'HTTP POST
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: ICreateAuthorResponse, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_12.create_author
*/
export async function createAuthor(
    request: ICreateAuthorRequest
) : Promise<{status: number, response: ICreateAuthorResponse, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-12/create-author", {
        method: "POST",
        headers: {
            "Content-Type": "application/json"
        },
        body: JSON.stringify(request)
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as ICreateAuthorResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_12.get_author(
*     _author_id integer
* )
* returns record
* 
* @remarks
* comment on function example_12.get_author is 'HTTP GET
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IGetAuthorResponse, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_12.get_author
*/
export async function getAuthor(
    request: IGetAuthorRequest
) : Promise<{status: number, response: IGetAuthorResponse, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-12/get-author" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_12.get_author_info(
*     _author_id integer
* )
* returns record
* 
* @remarks
* comment on function example_12.get_author_info is 'HTTP GET
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IGetAuthorInfoResponse, error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_12.get_author_info
*/
export async function getAuthorInfo(
    request: IGetAuthorInfoRequest
) : Promise<{status: number, response: IGetAuthorInfoResponse, error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-12/get-author-info" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorInfoResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_12.get_authors(
*     _author_author_id integer,
*     _author_first_name text,
*     _author_last_name text
* )
* returns table(
*     author_id integer,
*     first_name text,
*     last_name text
* )
* 
* @remarks
* comment on function example_12.get_authors is 'HTTP GET
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IGetAuthorsResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_12.get_authors
*/
export async function getAuthors(
    request: IGetAuthorsRequest
) : Promise<{status: number, response: IGetAuthorsResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-12/get-authors" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_12.get_authors_and_books(
*     _author_id integer
* )
* returns table(
*     author integer,
*     author text,
*     author text,
*     books example_12.books[]
* )
* 
* @remarks
* comment on function example_12.get_authors_and_books is 'HTTP GET
* @nested';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IGetAuthorsAndBooksResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_12.get_authors_and_books
*/
export async function getAuthorsAndBooks(
    request: IGetAuthorsAndBooksRequest
) : Promise<{status: number, response: IGetAuthorsAndBooksResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-12/get-authors-and-books" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorsAndBooksResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_12.get_authors_and_books_and_reviews(
*     _author_id integer
* )
* returns table(
*     author integer,
*     author text,
*     author text,
*     books example_12.book_details[]
* )
* 
* @remarks
* comment on function example_12.get_authors_and_books_and_reviews is 'HTTP GET
* @nested';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IGetAuthorsAndBooksAndReviewsResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_12.get_authors_and_books_and_reviews
*/
export async function getAuthorsAndBooksAndReviews(
    request: IGetAuthorsAndBooksAndReviewsRequest
) : Promise<{status: number, response: IGetAuthorsAndBooksAndReviewsResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-12/get-authors-and-books-and-reviews" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorsAndBooksAndReviewsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_12.get_authors_with_details(
*     _author_id integer
* )
* returns table(
*     author integer,
*     author text,
*     author text,
*     books integer
* )
* 
* @remarks
* comment on function example_12.get_authors_with_details is 'HTTP GET
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IGetAuthorsWithDetailsResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_12.get_authors_with_details
*/
export async function getAuthorsWithDetails(
    request: IGetAuthorsWithDetailsRequest
) : Promise<{status: number, response: IGetAuthorsWithDetailsResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-12/get-authors-with-details" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorsWithDetailsResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_12.get_authors_with_details_nested(
*     _author_id integer
* )
* returns table(
*     author integer,
*     author text,
*     author text,
*     books integer
* )
* 
* @remarks
* comment on function example_12.get_authors_with_details_nested is 'HTTP GET
* @nested';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IGetAuthorsWithDetailsNestedResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_12.get_authors_with_details_nested
*/
export async function getAuthorsWithDetailsNested(
    request: IGetAuthorsWithDetailsNestedRequest
) : Promise<{status: number, response: IGetAuthorsWithDetailsNestedResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-12/get-authors-with-details-nested" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorsWithDetailsNestedResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_12.get_authors_with_details_type(
*     _author_id integer
* )
* returns table(
*     author integer,
*     author text,
*     author text,
*     books_info integer,
*     books_info integer,
*     books_info numeric
* )
* 
* @remarks
* comment on function example_12.get_authors_with_details_type is 'HTTP GET
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IGetAuthorsWithDetailsTypeResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_12.get_authors_with_details_type
*/
export async function getAuthorsWithDetailsType(
    request: IGetAuthorsWithDetailsTypeRequest
) : Promise<{status: number, response: IGetAuthorsWithDetailsTypeResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-12/get-authors-with-details-type" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorsWithDetailsTypeResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

/**
* function example_12.get_authors_with_details_type_nested(
*     _author_id integer
* )
* returns table(
*     author integer,
*     author text,
*     author text,
*     books_info integer,
*     books_info integer,
*     books_info numeric
* )
* 
* @remarks
* comment on function example_12.get_authors_with_details_type_nested is 'HTTP GET
* @nested';
* 
* @param request - Object containing request parameters.
* @returns {status: number, response: IGetAuthorsWithDetailsTypeNestedResponse[], error: {status: number; title: string; detail?: string | null} | undefined}
* 
* @see FUNCTION example_12.get_authors_with_details_type_nested
*/
export async function getAuthorsWithDetailsTypeNested(
    request: IGetAuthorsWithDetailsTypeNestedRequest
) : Promise<{status: number, response: IGetAuthorsWithDetailsTypeNestedResponse[], error: {status: number; title: string; detail?: string | null} | undefined}> {
    const response = await fetch(baseUrl + "/api/example-12/get-authors-with-details-type-nested" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetAuthorsWithDetailsTypeNestedResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as {status: number; title: string; detail?: string | null} : undefined
    };
}

