// autogenerated at 2026-06-23T11:16:48.8821800+02:00


const baseUrl = "";
const parseQuery = (query: Record<any, any>) => "?" + Object.keys(query ? query : {})
    .map(key => {
        const value = (query[key] != null ? query[key] : "") as string;
        if (Array.isArray(value)) {
            return value.map((s: string) => s ? `${key}=${encodeURIComponent(s)}` : `${key}=`).join("&");
        }
        return `${key}=${encodeURIComponent(value)}`;
    })
    .join("&");

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

interface IBestLaptopRequest {
    responseBody?: string | null;
    responseStatusCode?: number | null;
    responseSuccess?: boolean | null;
    responseErrorMessage?: string | null;
}

interface IBestLaptopResponse {
    title: string | null;
    price: number | null;
    rating: number | null;
    score: number | null;
}


/**
* function example_16.best_laptop(
*     _response_body text DEFAULT NULL::example_16.laptops_api,
*     _response_status_code integer,
*     _response_success boolean,
*     _response_error_message text
* )
* returns table(
*     title text,
*     price numeric,
*     rating numeric,
*     score numeric
* )
* 
* @remarks
* comment on function example_16.best_laptop is 'HTTP GET /best-laptop
* allow_anonymous
* single';
* 
* @param request - Object containing request parameters.
* @returns {ApiResult<IBestLaptopResponse>}
* 
* @see FUNCTION example_16.best_laptop
*/
export async function bestLaptop(
    request: IBestLaptopRequest
) : Promise<ApiResult<IBestLaptopResponse>> {
    const response = await fetch(baseUrl + "/best-laptop" + parseQuery(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.ok ? await response.json() as IBestLaptopResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

