// autogenerated at 2026-03-31T19:24:45.9159860+02:00


const baseUrl = "";

type ApiError = {status: number; title: string; detail?: string | null};
type ApiResult<T> = {status: number, response: T, error: ApiError | undefined};

interface IGetUsersResponse {
    userId: number | null;
    username: string | null;
    email: string | null;
    roles: string[] | null;
    passwordHash: string | null;
    lastLogin: string | null;
    lastLoginProvider: string | null;
    isThisMe: boolean | null;
}

interface ILoginRequest {
    scheme: string | null;
    username: string | null;
    password: string | null;
}

interface IWhoAmIResponse {
    userId: number | null;
    username: string | null;
    email: string | null;
    roles: string[] | null;
    lastLogin: string | null;
    lastLoginProvider: string | null;
}


/**
* SQL file: ../../npgsqlrest-docs/examples/4_passwords_tokens_roles_sql_file/sql/get-users.sql
* 
* @remarks
*  HTTP GET
*  @authorize admin
* 
* @param parseRequest - Optional function to parse constructed request before making the request.
* @returns {ApiResult<IGetUsersResponse[]>}
* 
* @see SQLFILE public.get-users
*/
export async function getUsers(
    parseRequest: (request: RequestInit) => RequestInit = request => request
) : Promise<ApiResult<IGetUsersResponse[]>> {
    const response = await fetch(baseUrl + "/api/get-users", parseRequest({
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    }));
    return {
        status: response.status,
        response: response.ok ? await response.json() as IGetUsersResponse[] : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/4_passwords_tokens_roles_sql_file/sql/login.sql
* 
* @remarks
* HTTP POST
* @login
* @allow_anonymous
* @param $1 scheme text
* @param $2 username text
* @define_param password text
*  configured schemes are 'cookies', 'token' and 'jwt' and any other scheme is rejected (404)
* 
* @param request - Object containing request parameters.
* @param parseRequest - Optional function to parse constructed request before making the request.
* @returns {ApiResult<string>}
* 
* @see SQLFILE public.login
*/
export async function login(
    request: ILoginRequest,
    parseRequest: (request: RequestInit) => RequestInit = request => request
) : Promise<ApiResult<string>> {
    const response = await fetch(baseUrl + "/api/login", parseRequest({
        method: "POST",
        body: JSON.stringify(request)
    }));
    return {
        status: response.status,
        response: response.ok ? await response.text() : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/4_passwords_tokens_roles_sql_file/sql/logout.sql
* 
* @remarks
*  HTTP POST
*  @logout
*  @authorize
* 
* @param parseRequest - Optional function to parse constructed request before making the request.
* @returns {status: number, error: ApiError | undefined}
* 
* @see SQLFILE public.logout
*/
export async function logout(
    parseRequest: (request: RequestInit) => RequestInit = request => request
) : Promise<{status: number, error: ApiError | undefined}> {
    const response = await fetch(baseUrl + "/api/logout", parseRequest({
        method: "POST",
    }));
    return {
        status: response.status,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

/**
* SQL file: ../../npgsqlrest-docs/examples/4_passwords_tokens_roles_sql_file/sql/who-am-i.sql
* 
* @remarks
*  HTTP GET
*  @authorize
*  @single_result
*  user claims are stored in current settings by npgsqlrest
* 
* @param parseRequest - Optional function to parse constructed request before making the request.
* @returns {ApiResult<IWhoAmIResponse>}
* 
* @see SQLFILE public.who-am-i
*/
export async function whoAmI(
    parseRequest: (request: RequestInit) => RequestInit = request => request
) : Promise<ApiResult<IWhoAmIResponse>> {
    const response = await fetch(baseUrl + "/api/who-am-i", parseRequest({
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    }));
    return {
        status: response.status,
        response: response.ok ? await response.json() as IWhoAmIResponse : undefined!,
        error: !response.ok && response.headers.get("content-length") !== "0" ? await response.json() as ApiError : undefined
    };
}

